---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: ack-fsx-writer
  namespace: default
rules:
- apiGroups:
  - fsx.services.k8s.aws
  resources:
  - filesystems
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fsx.services.k8s.aws
  resources:
  - filesystems
  verbs:
  - get
  - patch
  - update
