// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package file_system

import (
	"bytes"

	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	acktags "github.com/aws-controllers-k8s/runtime/pkg/tags"
	"k8s.io/apimachinery/pkg/api/equality"
)

// Hack to avoid import errors during build...
var (
	_ = &bytes.Buffer{}
	_ = &acktags.Tags{}
)

// newResourceDelta returns a new `ackcompare.Delta` used to compare two
// resources
func newResourceDelta(
	a *resource,
	b *resource,
) *ackcompare.Delta {
	delta := ackcompare.NewDelta()
	if (a == nil && b != nil) ||
		(a != nil && b == nil) {
		delta.Add("", a, b)
		return delta
	}
	customPreCompare(delta, a, b)

	if ackcompare.HasNilDifference(a.ko.Spec.FileSystemType, b.ko.Spec.FileSystemType) {
		delta.Add("Spec.FileSystemType", a.ko.Spec.FileSystemType, b.ko.Spec.FileSystemType)
	} else if a.ko.Spec.FileSystemType != nil && b.ko.Spec.FileSystemType != nil {
		if *a.ko.Spec.FileSystemType != *b.ko.Spec.FileSystemType {
			delta.Add("Spec.FileSystemType", a.ko.Spec.FileSystemType, b.ko.Spec.FileSystemType)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.FileSystemTypeVersion, b.ko.Spec.FileSystemTypeVersion) {
		delta.Add("Spec.FileSystemTypeVersion", a.ko.Spec.FileSystemTypeVersion, b.ko.Spec.FileSystemTypeVersion)
	} else if a.ko.Spec.FileSystemTypeVersion != nil && b.ko.Spec.FileSystemTypeVersion != nil {
		if *a.ko.Spec.FileSystemTypeVersion != *b.ko.Spec.FileSystemTypeVersion {
			delta.Add("Spec.FileSystemTypeVersion", a.ko.Spec.FileSystemTypeVersion, b.ko.Spec.FileSystemTypeVersion)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.KMSKeyID, b.ko.Spec.KMSKeyID) {
		delta.Add("Spec.KMSKeyID", a.ko.Spec.KMSKeyID, b.ko.Spec.KMSKeyID)
	} else if a.ko.Spec.KMSKeyID != nil && b.ko.Spec.KMSKeyID != nil {
		if *a.ko.Spec.KMSKeyID != *b.ko.Spec.KMSKeyID {
			delta.Add("Spec.KMSKeyID", a.ko.Spec.KMSKeyID, b.ko.Spec.KMSKeyID)
		}
	}
	if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.KMSKeyRef, b.ko.Spec.KMSKeyRef) {
		delta.Add("Spec.KMSKeyRef", a.ko.Spec.KMSKeyRef, b.ko.Spec.KMSKeyRef)
	}
	if ackcompare.HasNilDifference(a.ko.Spec.LustreConfiguration, b.ko.Spec.LustreConfiguration) {
		delta.Add("Spec.LustreConfiguration", a.ko.Spec.LustreConfiguration, b.ko.Spec.LustreConfiguration)
	} else if a.ko.Spec.LustreConfiguration != nil && b.ko.Spec.LustreConfiguration != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.LustreConfiguration.AutoImportPolicy, b.ko.Spec.LustreConfiguration.AutoImportPolicy) {
			delta.Add("Spec.LustreConfiguration.AutoImportPolicy", a.ko.Spec.LustreConfiguration.AutoImportPolicy, b.ko.Spec.LustreConfiguration.AutoImportPolicy)
		} else if a.ko.Spec.LustreConfiguration.AutoImportPolicy != nil && b.ko.Spec.LustreConfiguration.AutoImportPolicy != nil {
			if *a.ko.Spec.LustreConfiguration.AutoImportPolicy != *b.ko.Spec.LustreConfiguration.AutoImportPolicy {
				delta.Add("Spec.LustreConfiguration.AutoImportPolicy", a.ko.Spec.LustreConfiguration.AutoImportPolicy, b.ko.Spec.LustreConfiguration.AutoImportPolicy)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.LustreConfiguration.AutomaticBackupRetentionDays, b.ko.Spec.LustreConfiguration.AutomaticBackupRetentionDays) {
			delta.Add("Spec.LustreConfiguration.AutomaticBackupRetentionDays", a.ko.Spec.LustreConfiguration.AutomaticBackupRetentionDays, b.ko.Spec.LustreConfiguration.AutomaticBackupRetentionDays)
		} else if a.ko.Spec.LustreConfiguration.AutomaticBackupRetentionDays != nil && b.ko.Spec.LustreConfiguration.AutomaticBackupRetentionDays != nil {
			if *a.ko.Spec.LustreConfiguration.AutomaticBackupRetentionDays != *b.ko.Spec.LustreConfiguration.AutomaticBackupRetentionDays {
				delta.Add("Spec.LustreConfiguration.AutomaticBackupRetentionDays", a.ko.Spec.LustreConfiguration.AutomaticBackupRetentionDays, b.ko.Spec.LustreConfiguration.AutomaticBackupRetentionDays)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.LustreConfiguration.CopyTagsToBackups, b.ko.Spec.LustreConfiguration.CopyTagsToBackups) {
			delta.Add("Spec.LustreConfiguration.CopyTagsToBackups", a.ko.Spec.LustreConfiguration.CopyTagsToBackups, b.ko.Spec.LustreConfiguration.CopyTagsToBackups)
		} else if a.ko.Spec.LustreConfiguration.CopyTagsToBackups != nil && b.ko.Spec.LustreConfiguration.CopyTagsToBackups != nil {
			if *a.ko.Spec.LustreConfiguration.CopyTagsToBackups != *b.ko.Spec.LustreConfiguration.CopyTagsToBackups {
				delta.Add("Spec.LustreConfiguration.CopyTagsToBackups", a.ko.Spec.LustreConfiguration.CopyTagsToBackups, b.ko.Spec.LustreConfiguration.CopyTagsToBackups)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.LustreConfiguration.DailyAutomaticBackupStartTime, b.ko.Spec.LustreConfiguration.DailyAutomaticBackupStartTime) {
			delta.Add("Spec.LustreConfiguration.DailyAutomaticBackupStartTime", a.ko.Spec.LustreConfiguration.DailyAutomaticBackupStartTime, b.ko.Spec.LustreConfiguration.DailyAutomaticBackupStartTime)
		} else if a.ko.Spec.LustreConfiguration.DailyAutomaticBackupStartTime != nil && b.ko.Spec.LustreConfiguration.DailyAutomaticBackupStartTime != nil {
			if *a.ko.Spec.LustreConfiguration.DailyAutomaticBackupStartTime != *b.ko.Spec.LustreConfiguration.DailyAutomaticBackupStartTime {
				delta.Add("Spec.LustreConfiguration.DailyAutomaticBackupStartTime", a.ko.Spec.LustreConfiguration.DailyAutomaticBackupStartTime, b.ko.Spec.LustreConfiguration.DailyAutomaticBackupStartTime)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.LustreConfiguration.DataCompressionType, b.ko.Spec.LustreConfiguration.DataCompressionType) {
			delta.Add("Spec.LustreConfiguration.DataCompressionType", a.ko.Spec.LustreConfiguration.DataCompressionType, b.ko.Spec.LustreConfiguration.DataCompressionType)
		} else if a.ko.Spec.LustreConfiguration.DataCompressionType != nil && b.ko.Spec.LustreConfiguration.DataCompressionType != nil {
			if *a.ko.Spec.LustreConfiguration.DataCompressionType != *b.ko.Spec.LustreConfiguration.DataCompressionType {
				delta.Add("Spec.LustreConfiguration.DataCompressionType", a.ko.Spec.LustreConfiguration.DataCompressionType, b.ko.Spec.LustreConfiguration.DataCompressionType)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.LustreConfiguration.DataReadCacheConfiguration, b.ko.Spec.LustreConfiguration.DataReadCacheConfiguration) {
			delta.Add("Spec.LustreConfiguration.DataReadCacheConfiguration", a.ko.Spec.LustreConfiguration.DataReadCacheConfiguration, b.ko.Spec.LustreConfiguration.DataReadCacheConfiguration)
		} else if a.ko.Spec.LustreConfiguration.DataReadCacheConfiguration != nil && b.ko.Spec.LustreConfiguration.DataReadCacheConfiguration != nil {
			if ackcompare.HasNilDifference(a.ko.Spec.LustreConfiguration.DataReadCacheConfiguration.SizeGiB, b.ko.Spec.LustreConfiguration.DataReadCacheConfiguration.SizeGiB) {
				delta.Add("Spec.LustreConfiguration.DataReadCacheConfiguration.SizeGiB", a.ko.Spec.LustreConfiguration.DataReadCacheConfiguration.SizeGiB, b.ko.Spec.LustreConfiguration.DataReadCacheConfiguration.SizeGiB)
			} else if a.ko.Spec.LustreConfiguration.DataReadCacheConfiguration.SizeGiB != nil && b.ko.Spec.LustreConfiguration.DataReadCacheConfiguration.SizeGiB != nil {
				if *a.ko.Spec.LustreConfiguration.DataReadCacheConfiguration.SizeGiB != *b.ko.Spec.LustreConfiguration.DataReadCacheConfiguration.SizeGiB {
					delta.Add("Spec.LustreConfiguration.DataReadCacheConfiguration.SizeGiB", a.ko.Spec.LustreConfiguration.DataReadCacheConfiguration.SizeGiB, b.ko.Spec.LustreConfiguration.DataReadCacheConfiguration.SizeGiB)
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.LustreConfiguration.DataReadCacheConfiguration.SizingMode, b.ko.Spec.LustreConfiguration.DataReadCacheConfiguration.SizingMode) {
				delta.Add("Spec.LustreConfiguration.DataReadCacheConfiguration.SizingMode", a.ko.Spec.LustreConfiguration.DataReadCacheConfiguration.SizingMode, b.ko.Spec.LustreConfiguration.DataReadCacheConfiguration.SizingMode)
			} else if a.ko.Spec.LustreConfiguration.DataReadCacheConfiguration.SizingMode != nil && b.ko.Spec.LustreConfiguration.DataReadCacheConfiguration.SizingMode != nil {
				if *a.ko.Spec.LustreConfiguration.DataReadCacheConfiguration.SizingMode != *b.ko.Spec.LustreConfiguration.DataReadCacheConfiguration.SizingMode {
					delta.Add("Spec.LustreConfiguration.DataReadCacheConfiguration.SizingMode", a.ko.Spec.LustreConfiguration.DataReadCacheConfiguration.SizingMode, b.ko.Spec.LustreConfiguration.DataReadCacheConfiguration.SizingMode)
				}
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.LustreConfiguration.DeploymentType, b.ko.Spec.LustreConfiguration.DeploymentType) {
			delta.Add("Spec.LustreConfiguration.DeploymentType", a.ko.Spec.LustreConfiguration.DeploymentType, b.ko.Spec.LustreConfiguration.DeploymentType)
		} else if a.ko.Spec.LustreConfiguration.DeploymentType != nil && b.ko.Spec.LustreConfiguration.DeploymentType != nil {
			if *a.ko.Spec.LustreConfiguration.DeploymentType != *b.ko.Spec.LustreConfiguration.DeploymentType {
				delta.Add("Spec.LustreConfiguration.DeploymentType", a.ko.Spec.LustreConfiguration.DeploymentType, b.ko.Spec.LustreConfiguration.DeploymentType)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.LustreConfiguration.DriveCacheType, b.ko.Spec.LustreConfiguration.DriveCacheType) {
			delta.Add("Spec.LustreConfiguration.DriveCacheType", a.ko.Spec.LustreConfiguration.DriveCacheType, b.ko.Spec.LustreConfiguration.DriveCacheType)
		} else if a.ko.Spec.LustreConfiguration.DriveCacheType != nil && b.ko.Spec.LustreConfiguration.DriveCacheType != nil {
			if *a.ko.Spec.LustreConfiguration.DriveCacheType != *b.ko.Spec.LustreConfiguration.DriveCacheType {
				delta.Add("Spec.LustreConfiguration.DriveCacheType", a.ko.Spec.LustreConfiguration.DriveCacheType, b.ko.Spec.LustreConfiguration.DriveCacheType)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.LustreConfiguration.EfaEnabled, b.ko.Spec.LustreConfiguration.EfaEnabled) {
			delta.Add("Spec.LustreConfiguration.EfaEnabled", a.ko.Spec.LustreConfiguration.EfaEnabled, b.ko.Spec.LustreConfiguration.EfaEnabled)
		} else if a.ko.Spec.LustreConfiguration.EfaEnabled != nil && b.ko.Spec.LustreConfiguration.EfaEnabled != nil {
			if *a.ko.Spec.LustreConfiguration.EfaEnabled != *b.ko.Spec.LustreConfiguration.EfaEnabled {
				delta.Add("Spec.LustreConfiguration.EfaEnabled", a.ko.Spec.LustreConfiguration.EfaEnabled, b.ko.Spec.LustreConfiguration.EfaEnabled)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.LustreConfiguration.ExportPath, b.ko.Spec.LustreConfiguration.ExportPath) {
			delta.Add("Spec.LustreConfiguration.ExportPath", a.ko.Spec.LustreConfiguration.ExportPath, b.ko.Spec.LustreConfiguration.ExportPath)
		} else if a.ko.Spec.LustreConfiguration.ExportPath != nil && b.ko.Spec.LustreConfiguration.ExportPath != nil {
			if *a.ko.Spec.LustreConfiguration.ExportPath != *b.ko.Spec.LustreConfiguration.ExportPath {
				delta.Add("Spec.LustreConfiguration.ExportPath", a.ko.Spec.LustreConfiguration.ExportPath, b.ko.Spec.LustreConfiguration.ExportPath)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.LustreConfiguration.ImportPath, b.ko.Spec.LustreConfiguration.ImportPath) {
			delta.Add("Spec.LustreConfiguration.ImportPath", a.ko.Spec.LustreConfiguration.ImportPath, b.ko.Spec.LustreConfiguration.ImportPath)
		} else if a.ko.Spec.LustreConfiguration.ImportPath != nil && b.ko.Spec.LustreConfiguration.ImportPath != nil {
			if *a.ko.Spec.LustreConfiguration.ImportPath != *b.ko.Spec.LustreConfiguration.ImportPath {
				delta.Add("Spec.LustreConfiguration.ImportPath", a.ko.Spec.LustreConfiguration.ImportPath, b.ko.Spec.LustreConfiguration.ImportPath)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.LustreConfiguration.ImportedFileChunkSize, b.ko.Spec.LustreConfiguration.ImportedFileChunkSize) {
			delta.Add("Spec.LustreConfiguration.ImportedFileChunkSize", a.ko.Spec.LustreConfiguration.ImportedFileChunkSize, b.ko.Spec.LustreConfiguration.ImportedFileChunkSize)
		} else if a.ko.Spec.LustreConfiguration.ImportedFileChunkSize != nil && b.ko.Spec.LustreConfiguration.ImportedFileChunkSize != nil {
			if *a.ko.Spec.LustreConfiguration.ImportedFileChunkSize != *b.ko.Spec.LustreConfiguration.ImportedFileChunkSize {
				delta.Add("Spec.LustreConfiguration.ImportedFileChunkSize", a.ko.Spec.LustreConfiguration.ImportedFileChunkSize, b.ko.Spec.LustreConfiguration.ImportedFileChunkSize)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.LustreConfiguration.LogConfiguration, b.ko.Spec.LustreConfiguration.LogConfiguration) {
			delta.Add("Spec.LustreConfiguration.LogConfiguration", a.ko.Spec.LustreConfiguration.LogConfiguration, b.ko.Spec.LustreConfiguration.LogConfiguration)
		} else if a.ko.Spec.LustreConfiguration.LogConfiguration != nil && b.ko.Spec.LustreConfiguration.LogConfiguration != nil {
			if ackcompare.HasNilDifference(a.ko.Spec.LustreConfiguration.LogConfiguration.Destination, b.ko.Spec.LustreConfiguration.LogConfiguration.Destination) {
				delta.Add("Spec.LustreConfiguration.LogConfiguration.Destination", a.ko.Spec.LustreConfiguration.LogConfiguration.Destination, b.ko.Spec.LustreConfiguration.LogConfiguration.Destination)
			} else if a.ko.Spec.LustreConfiguration.LogConfiguration.Destination != nil && b.ko.Spec.LustreConfiguration.LogConfiguration.Destination != nil {
				if *a.ko.Spec.LustreConfiguration.LogConfiguration.Destination != *b.ko.Spec.LustreConfiguration.LogConfiguration.Destination {
					delta.Add("Spec.LustreConfiguration.LogConfiguration.Destination", a.ko.Spec.LustreConfiguration.LogConfiguration.Destination, b.ko.Spec.LustreConfiguration.LogConfiguration.Destination)
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.LustreConfiguration.LogConfiguration.Level, b.ko.Spec.LustreConfiguration.LogConfiguration.Level) {
				delta.Add("Spec.LustreConfiguration.LogConfiguration.Level", a.ko.Spec.LustreConfiguration.LogConfiguration.Level, b.ko.Spec.LustreConfiguration.LogConfiguration.Level)
			} else if a.ko.Spec.LustreConfiguration.LogConfiguration.Level != nil && b.ko.Spec.LustreConfiguration.LogConfiguration.Level != nil {
				if *a.ko.Spec.LustreConfiguration.LogConfiguration.Level != *b.ko.Spec.LustreConfiguration.LogConfiguration.Level {
					delta.Add("Spec.LustreConfiguration.LogConfiguration.Level", a.ko.Spec.LustreConfiguration.LogConfiguration.Level, b.ko.Spec.LustreConfiguration.LogConfiguration.Level)
				}
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.LustreConfiguration.MetadataConfiguration, b.ko.Spec.LustreConfiguration.MetadataConfiguration) {
			delta.Add("Spec.LustreConfiguration.MetadataConfiguration", a.ko.Spec.LustreConfiguration.MetadataConfiguration, b.ko.Spec.LustreConfiguration.MetadataConfiguration)
		} else if a.ko.Spec.LustreConfiguration.MetadataConfiguration != nil && b.ko.Spec.LustreConfiguration.MetadataConfiguration != nil {
			if ackcompare.HasNilDifference(a.ko.Spec.LustreConfiguration.MetadataConfiguration.IOPS, b.ko.Spec.LustreConfiguration.MetadataConfiguration.IOPS) {
				delta.Add("Spec.LustreConfiguration.MetadataConfiguration.IOPS", a.ko.Spec.LustreConfiguration.MetadataConfiguration.IOPS, b.ko.Spec.LustreConfiguration.MetadataConfiguration.IOPS)
			} else if a.ko.Spec.LustreConfiguration.MetadataConfiguration.IOPS != nil && b.ko.Spec.LustreConfiguration.MetadataConfiguration.IOPS != nil {
				if *a.ko.Spec.LustreConfiguration.MetadataConfiguration.IOPS != *b.ko.Spec.LustreConfiguration.MetadataConfiguration.IOPS {
					delta.Add("Spec.LustreConfiguration.MetadataConfiguration.IOPS", a.ko.Spec.LustreConfiguration.MetadataConfiguration.IOPS, b.ko.Spec.LustreConfiguration.MetadataConfiguration.IOPS)
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.LustreConfiguration.MetadataConfiguration.Mode, b.ko.Spec.LustreConfiguration.MetadataConfiguration.Mode) {
				delta.Add("Spec.LustreConfiguration.MetadataConfiguration.Mode", a.ko.Spec.LustreConfiguration.MetadataConfiguration.Mode, b.ko.Spec.LustreConfiguration.MetadataConfiguration.Mode)
			} else if a.ko.Spec.LustreConfiguration.MetadataConfiguration.Mode != nil && b.ko.Spec.LustreConfiguration.MetadataConfiguration.Mode != nil {
				if *a.ko.Spec.LustreConfiguration.MetadataConfiguration.Mode != *b.ko.Spec.LustreConfiguration.MetadataConfiguration.Mode {
					delta.Add("Spec.LustreConfiguration.MetadataConfiguration.Mode", a.ko.Spec.LustreConfiguration.MetadataConfiguration.Mode, b.ko.Spec.LustreConfiguration.MetadataConfiguration.Mode)
				}
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.LustreConfiguration.PerUnitStorageThroughput, b.ko.Spec.LustreConfiguration.PerUnitStorageThroughput) {
			delta.Add("Spec.LustreConfiguration.PerUnitStorageThroughput", a.ko.Spec.LustreConfiguration.PerUnitStorageThroughput, b.ko.Spec.LustreConfiguration.PerUnitStorageThroughput)
		} else if a.ko.Spec.LustreConfiguration.PerUnitStorageThroughput != nil && b.ko.Spec.LustreConfiguration.PerUnitStorageThroughput != nil {
			if *a.ko.Spec.LustreConfiguration.PerUnitStorageThroughput != *b.ko.Spec.LustreConfiguration.PerUnitStorageThroughput {
				delta.Add("Spec.LustreConfiguration.PerUnitStorageThroughput", a.ko.Spec.LustreConfiguration.PerUnitStorageThroughput, b.ko.Spec.LustreConfiguration.PerUnitStorageThroughput)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.LustreConfiguration.RootSquashConfiguration, b.ko.Spec.LustreConfiguration.RootSquashConfiguration) {
			delta.Add("Spec.LustreConfiguration.RootSquashConfiguration", a.ko.Spec.LustreConfiguration.RootSquashConfiguration, b.ko.Spec.LustreConfiguration.RootSquashConfiguration)
		} else if a.ko.Spec.LustreConfiguration.RootSquashConfiguration != nil && b.ko.Spec.LustreConfiguration.RootSquashConfiguration != nil {
			if len(a.ko.Spec.LustreConfiguration.RootSquashConfiguration.NoSquashNids) != len(b.ko.Spec.LustreConfiguration.RootSquashConfiguration.NoSquashNids) {
				delta.Add("Spec.LustreConfiguration.RootSquashConfiguration.NoSquashNids", a.ko.Spec.LustreConfiguration.RootSquashConfiguration.NoSquashNids, b.ko.Spec.LustreConfiguration.RootSquashConfiguration.NoSquashNids)
			} else if len(a.ko.Spec.LustreConfiguration.RootSquashConfiguration.NoSquashNids) > 0 {
				if !ackcompare.SliceStringPEqual(a.ko.Spec.LustreConfiguration.RootSquashConfiguration.NoSquashNids, b.ko.Spec.LustreConfiguration.RootSquashConfiguration.NoSquashNids) {
					delta.Add("Spec.LustreConfiguration.RootSquashConfiguration.NoSquashNids", a.ko.Spec.LustreConfiguration.RootSquashConfiguration.NoSquashNids, b.ko.Spec.LustreConfiguration.RootSquashConfiguration.NoSquashNids)
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.LustreConfiguration.RootSquashConfiguration.RootSquash, b.ko.Spec.LustreConfiguration.RootSquashConfiguration.RootSquash) {
				delta.Add("Spec.LustreConfiguration.RootSquashConfiguration.RootSquash", a.ko.Spec.LustreConfiguration.RootSquashConfiguration.RootSquash, b.ko.Spec.LustreConfiguration.RootSquashConfiguration.RootSquash)
			} else if a.ko.Spec.LustreConfiguration.RootSquashConfiguration.RootSquash != nil && b.ko.Spec.LustreConfiguration.RootSquashConfiguration.RootSquash != nil {
				if *a.ko.Spec.LustreConfiguration.RootSquashConfiguration.RootSquash != *b.ko.Spec.LustreConfiguration.RootSquashConfiguration.RootSquash {
					delta.Add("Spec.LustreConfiguration.RootSquashConfiguration.RootSquash", a.ko.Spec.LustreConfiguration.RootSquashConfiguration.RootSquash, b.ko.Spec.LustreConfiguration.RootSquashConfiguration.RootSquash)
				}
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.LustreConfiguration.ThroughputCapacity, b.ko.Spec.LustreConfiguration.ThroughputCapacity) {
			delta.Add("Spec.LustreConfiguration.ThroughputCapacity", a.ko.Spec.LustreConfiguration.ThroughputCapacity, b.ko.Spec.LustreConfiguration.ThroughputCapacity)
		} else if a.ko.Spec.LustreConfiguration.ThroughputCapacity != nil && b.ko.Spec.LustreConfiguration.ThroughputCapacity != nil {
			if *a.ko.Spec.LustreConfiguration.ThroughputCapacity != *b.ko.Spec.LustreConfiguration.ThroughputCapacity {
				delta.Add("Spec.LustreConfiguration.ThroughputCapacity", a.ko.Spec.LustreConfiguration.ThroughputCapacity, b.ko.Spec.LustreConfiguration.ThroughputCapacity)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.LustreConfiguration.WeeklyMaintenanceStartTime, b.ko.Spec.LustreConfiguration.WeeklyMaintenanceStartTime) {
			delta.Add("Spec.LustreConfiguration.WeeklyMaintenanceStartTime", a.ko.Spec.LustreConfiguration.WeeklyMaintenanceStartTime, b.ko.Spec.LustreConfiguration.WeeklyMaintenanceStartTime)
		} else if a.ko.Spec.LustreConfiguration.WeeklyMaintenanceStartTime != nil && b.ko.Spec.LustreConfiguration.WeeklyMaintenanceStartTime != nil {
			if *a.ko.Spec.LustreConfiguration.WeeklyMaintenanceStartTime != *b.ko.Spec.LustreConfiguration.WeeklyMaintenanceStartTime {
				delta.Add("Spec.LustreConfiguration.WeeklyMaintenanceStartTime", a.ko.Spec.LustreConfiguration.WeeklyMaintenanceStartTime, b.ko.Spec.LustreConfiguration.WeeklyMaintenanceStartTime)
			}
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.NetworkType, b.ko.Spec.NetworkType) {
		delta.Add("Spec.NetworkType", a.ko.Spec.NetworkType, b.ko.Spec.NetworkType)
	} else if a.ko.Spec.NetworkType != nil && b.ko.Spec.NetworkType != nil {
		if *a.ko.Spec.NetworkType != *b.ko.Spec.NetworkType {
			delta.Add("Spec.NetworkType", a.ko.Spec.NetworkType, b.ko.Spec.NetworkType)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.OntapConfiguration, b.ko.Spec.OntapConfiguration) {
		delta.Add("Spec.OntapConfiguration", a.ko.Spec.OntapConfiguration, b.ko.Spec.OntapConfiguration)
	} else if a.ko.Spec.OntapConfiguration != nil && b.ko.Spec.OntapConfiguration != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.OntapConfiguration.AutomaticBackupRetentionDays, b.ko.Spec.OntapConfiguration.AutomaticBackupRetentionDays) {
			delta.Add("Spec.OntapConfiguration.AutomaticBackupRetentionDays", a.ko.Spec.OntapConfiguration.AutomaticBackupRetentionDays, b.ko.Spec.OntapConfiguration.AutomaticBackupRetentionDays)
		} else if a.ko.Spec.OntapConfiguration.AutomaticBackupRetentionDays != nil && b.ko.Spec.OntapConfiguration.AutomaticBackupRetentionDays != nil {
			if *a.ko.Spec.OntapConfiguration.AutomaticBackupRetentionDays != *b.ko.Spec.OntapConfiguration.AutomaticBackupRetentionDays {
				delta.Add("Spec.OntapConfiguration.AutomaticBackupRetentionDays", a.ko.Spec.OntapConfiguration.AutomaticBackupRetentionDays, b.ko.Spec.OntapConfiguration.AutomaticBackupRetentionDays)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.OntapConfiguration.DailyAutomaticBackupStartTime, b.ko.Spec.OntapConfiguration.DailyAutomaticBackupStartTime) {
			delta.Add("Spec.OntapConfiguration.DailyAutomaticBackupStartTime", a.ko.Spec.OntapConfiguration.DailyAutomaticBackupStartTime, b.ko.Spec.OntapConfiguration.DailyAutomaticBackupStartTime)
		} else if a.ko.Spec.OntapConfiguration.DailyAutomaticBackupStartTime != nil && b.ko.Spec.OntapConfiguration.DailyAutomaticBackupStartTime != nil {
			if *a.ko.Spec.OntapConfiguration.DailyAutomaticBackupStartTime != *b.ko.Spec.OntapConfiguration.DailyAutomaticBackupStartTime {
				delta.Add("Spec.OntapConfiguration.DailyAutomaticBackupStartTime", a.ko.Spec.OntapConfiguration.DailyAutomaticBackupStartTime, b.ko.Spec.OntapConfiguration.DailyAutomaticBackupStartTime)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.OntapConfiguration.DeploymentType, b.ko.Spec.OntapConfiguration.DeploymentType) {
			delta.Add("Spec.OntapConfiguration.DeploymentType", a.ko.Spec.OntapConfiguration.DeploymentType, b.ko.Spec.OntapConfiguration.DeploymentType)
		} else if a.ko.Spec.OntapConfiguration.DeploymentType != nil && b.ko.Spec.OntapConfiguration.DeploymentType != nil {
			if *a.ko.Spec.OntapConfiguration.DeploymentType != *b.ko.Spec.OntapConfiguration.DeploymentType {
				delta.Add("Spec.OntapConfiguration.DeploymentType", a.ko.Spec.OntapConfiguration.DeploymentType, b.ko.Spec.OntapConfiguration.DeploymentType)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.OntapConfiguration.DiskIOPSConfiguration, b.ko.Spec.OntapConfiguration.DiskIOPSConfiguration) {
			delta.Add("Spec.OntapConfiguration.DiskIOPSConfiguration", a.ko.Spec.OntapConfiguration.DiskIOPSConfiguration, b.ko.Spec.OntapConfiguration.DiskIOPSConfiguration)
		} else if a.ko.Spec.OntapConfiguration.DiskIOPSConfiguration != nil && b.ko.Spec.OntapConfiguration.DiskIOPSConfiguration != nil {
			if ackcompare.HasNilDifference(a.ko.Spec.OntapConfiguration.DiskIOPSConfiguration.IOPS, b.ko.Spec.OntapConfiguration.DiskIOPSConfiguration.IOPS) {
				delta.Add("Spec.OntapConfiguration.DiskIOPSConfiguration.IOPS", a.ko.Spec.OntapConfiguration.DiskIOPSConfiguration.IOPS, b.ko.Spec.OntapConfiguration.DiskIOPSConfiguration.IOPS)
			} else if a.ko.Spec.OntapConfiguration.DiskIOPSConfiguration.IOPS != nil && b.ko.Spec.OntapConfiguration.DiskIOPSConfiguration.IOPS != nil {
				if *a.ko.Spec.OntapConfiguration.DiskIOPSConfiguration.IOPS != *b.ko.Spec.OntapConfiguration.DiskIOPSConfiguration.IOPS {
					delta.Add("Spec.OntapConfiguration.DiskIOPSConfiguration.IOPS", a.ko.Spec.OntapConfiguration.DiskIOPSConfiguration.IOPS, b.ko.Spec.OntapConfiguration.DiskIOPSConfiguration.IOPS)
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.OntapConfiguration.DiskIOPSConfiguration.Mode, b.ko.Spec.OntapConfiguration.DiskIOPSConfiguration.Mode) {
				delta.Add("Spec.OntapConfiguration.DiskIOPSConfiguration.Mode", a.ko.Spec.OntapConfiguration.DiskIOPSConfiguration.Mode, b.ko.Spec.OntapConfiguration.DiskIOPSConfiguration.Mode)
			} else if a.ko.Spec.OntapConfiguration.DiskIOPSConfiguration.Mode != nil && b.ko.Spec.OntapConfiguration.DiskIOPSConfiguration.Mode != nil {
				if *a.ko.Spec.OntapConfiguration.DiskIOPSConfiguration.Mode != *b.ko.Spec.OntapConfiguration.DiskIOPSConfiguration.Mode {
					delta.Add("Spec.OntapConfiguration.DiskIOPSConfiguration.Mode", a.ko.Spec.OntapConfiguration.DiskIOPSConfiguration.Mode, b.ko.Spec.OntapConfiguration.DiskIOPSConfiguration.Mode)
				}
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.OntapConfiguration.EndpointIPAddressRange, b.ko.Spec.OntapConfiguration.EndpointIPAddressRange) {
			delta.Add("Spec.OntapConfiguration.EndpointIPAddressRange", a.ko.Spec.OntapConfiguration.EndpointIPAddressRange, b.ko.Spec.OntapConfiguration.EndpointIPAddressRange)
		} else if a.ko.Spec.OntapConfiguration.EndpointIPAddressRange != nil && b.ko.Spec.OntapConfiguration.EndpointIPAddressRange != nil {
			if *a.ko.Spec.OntapConfiguration.EndpointIPAddressRange != *b.ko.Spec.OntapConfiguration.EndpointIPAddressRange {
				delta.Add("Spec.OntapConfiguration.EndpointIPAddressRange", a.ko.Spec.OntapConfiguration.EndpointIPAddressRange, b.ko.Spec.OntapConfiguration.EndpointIPAddressRange)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.OntapConfiguration.EndpointIPv6AddressRange, b.ko.Spec.OntapConfiguration.EndpointIPv6AddressRange) {
			delta.Add("Spec.OntapConfiguration.EndpointIPv6AddressRange", a.ko.Spec.OntapConfiguration.EndpointIPv6AddressRange, b.ko.Spec.OntapConfiguration.EndpointIPv6AddressRange)
		} else if a.ko.Spec.OntapConfiguration.EndpointIPv6AddressRange != nil && b.ko.Spec.OntapConfiguration.EndpointIPv6AddressRange != nil {
			if *a.ko.Spec.OntapConfiguration.EndpointIPv6AddressRange != *b.ko.Spec.OntapConfiguration.EndpointIPv6AddressRange {
				delta.Add("Spec.OntapConfiguration.EndpointIPv6AddressRange", a.ko.Spec.OntapConfiguration.EndpointIPv6AddressRange, b.ko.Spec.OntapConfiguration.EndpointIPv6AddressRange)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.OntapConfiguration.HAPairs, b.ko.Spec.OntapConfiguration.HAPairs) {
			delta.Add("Spec.OntapConfiguration.HAPairs", a.ko.Spec.OntapConfiguration.HAPairs, b.ko.Spec.OntapConfiguration.HAPairs)
		} else if a.ko.Spec.OntapConfiguration.HAPairs != nil && b.ko.Spec.OntapConfiguration.HAPairs != nil {
			if *a.ko.Spec.OntapConfiguration.HAPairs != *b.ko.Spec.OntapConfiguration.HAPairs {
				delta.Add("Spec.OntapConfiguration.HAPairs", a.ko.Spec.OntapConfiguration.HAPairs, b.ko.Spec.OntapConfiguration.HAPairs)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.OntapConfiguration.PreferredSubnetID, b.ko.Spec.OntapConfiguration.PreferredSubnetID) {
			delta.Add("Spec.OntapConfiguration.PreferredSubnetID", a.ko.Spec.OntapConfiguration.PreferredSubnetID, b.ko.Spec.OntapConfiguration.PreferredSubnetID)
		} else if a.ko.Spec.OntapConfiguration.PreferredSubnetID != nil && b.ko.Spec.OntapConfiguration.PreferredSubnetID != nil {
			if *a.ko.Spec.OntapConfiguration.PreferredSubnetID != *b.ko.Spec.OntapConfiguration.PreferredSubnetID {
				delta.Add("Spec.OntapConfiguration.PreferredSubnetID", a.ko.Spec.OntapConfiguration.PreferredSubnetID, b.ko.Spec.OntapConfiguration.PreferredSubnetID)
			}
		}
		if len(a.ko.Spec.OntapConfiguration.RouteTableIDs) != len(b.ko.Spec.OntapConfiguration.RouteTableIDs) {
			delta.Add("Spec.OntapConfiguration.RouteTableIDs", a.ko.Spec.OntapConfiguration.RouteTableIDs, b.ko.Spec.OntapConfiguration.RouteTableIDs)
		} else if len(a.ko.Spec.OntapConfiguration.RouteTableIDs) > 0 {
			if !ackcompare.SliceStringPEqual(a.ko.Spec.OntapConfiguration.RouteTableIDs, b.ko.Spec.OntapConfiguration.RouteTableIDs) {
				delta.Add("Spec.OntapConfiguration.RouteTableIDs", a.ko.Spec.OntapConfiguration.RouteTableIDs, b.ko.Spec.OntapConfiguration.RouteTableIDs)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.OntapConfiguration.ThroughputCapacity, b.ko.Spec.OntapConfiguration.ThroughputCapacity) {
			delta.Add("Spec.OntapConfiguration.ThroughputCapacity", a.ko.Spec.OntapConfiguration.ThroughputCapacity, b.ko.Spec.OntapConfiguration.ThroughputCapacity)
		} else if a.ko.Spec.OntapConfiguration.ThroughputCapacity != nil && b.ko.Spec.OntapConfiguration.ThroughputCapacity != nil {
			if *a.ko.Spec.OntapConfiguration.ThroughputCapacity != *b.ko.Spec.OntapConfiguration.ThroughputCapacity {
				delta.Add("Spec.OntapConfiguration.ThroughputCapacity", a.ko.Spec.OntapConfiguration.ThroughputCapacity, b.ko.Spec.OntapConfiguration.ThroughputCapacity)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.OntapConfiguration.ThroughputCapacityPerHAPair, b.ko.Spec.OntapConfiguration.ThroughputCapacityPerHAPair) {
			delta.Add("Spec.OntapConfiguration.ThroughputCapacityPerHAPair", a.ko.Spec.OntapConfiguration.ThroughputCapacityPerHAPair, b.ko.Spec.OntapConfiguration.ThroughputCapacityPerHAPair)
		} else if a.ko.Spec.OntapConfiguration.ThroughputCapacityPerHAPair != nil && b.ko.Spec.OntapConfiguration.ThroughputCapacityPerHAPair != nil {
			if *a.ko.Spec.OntapConfiguration.ThroughputCapacityPerHAPair != *b.ko.Spec.OntapConfiguration.ThroughputCapacityPerHAPair {
				delta.Add("Spec.OntapConfiguration.ThroughputCapacityPerHAPair", a.ko.Spec.OntapConfiguration.ThroughputCapacityPerHAPair, b.ko.Spec.OntapConfiguration.ThroughputCapacityPerHAPair)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.OntapConfiguration.WeeklyMaintenanceStartTime, b.ko.Spec.OntapConfiguration.WeeklyMaintenanceStartTime) {
			delta.Add("Spec.OntapConfiguration.WeeklyMaintenanceStartTime", a.ko.Spec.OntapConfiguration.WeeklyMaintenanceStartTime, b.ko.Spec.OntapConfiguration.WeeklyMaintenanceStartTime)
		} else if a.ko.Spec.OntapConfiguration.WeeklyMaintenanceStartTime != nil && b.ko.Spec.OntapConfiguration.WeeklyMaintenanceStartTime != nil {
			if *a.ko.Spec.OntapConfiguration.WeeklyMaintenanceStartTime != *b.ko.Spec.OntapConfiguration.WeeklyMaintenanceStartTime {
				delta.Add("Spec.OntapConfiguration.WeeklyMaintenanceStartTime", a.ko.Spec.OntapConfiguration.WeeklyMaintenanceStartTime, b.ko.Spec.OntapConfiguration.WeeklyMaintenanceStartTime)
			}
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.OpenZFSConfiguration, b.ko.Spec.OpenZFSConfiguration) {
		delta.Add("Spec.OpenZFSConfiguration", a.ko.Spec.OpenZFSConfiguration, b.ko.Spec.OpenZFSConfiguration)
	} else if a.ko.Spec.OpenZFSConfiguration != nil && b.ko.Spec.OpenZFSConfiguration != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.OpenZFSConfiguration.AutomaticBackupRetentionDays, b.ko.Spec.OpenZFSConfiguration.AutomaticBackupRetentionDays) {
			delta.Add("Spec.OpenZFSConfiguration.AutomaticBackupRetentionDays", a.ko.Spec.OpenZFSConfiguration.AutomaticBackupRetentionDays, b.ko.Spec.OpenZFSConfiguration.AutomaticBackupRetentionDays)
		} else if a.ko.Spec.OpenZFSConfiguration.AutomaticBackupRetentionDays != nil && b.ko.Spec.OpenZFSConfiguration.AutomaticBackupRetentionDays != nil {
			if *a.ko.Spec.OpenZFSConfiguration.AutomaticBackupRetentionDays != *b.ko.Spec.OpenZFSConfiguration.AutomaticBackupRetentionDays {
				delta.Add("Spec.OpenZFSConfiguration.AutomaticBackupRetentionDays", a.ko.Spec.OpenZFSConfiguration.AutomaticBackupRetentionDays, b.ko.Spec.OpenZFSConfiguration.AutomaticBackupRetentionDays)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.OpenZFSConfiguration.CopyTagsToBackups, b.ko.Spec.OpenZFSConfiguration.CopyTagsToBackups) {
			delta.Add("Spec.OpenZFSConfiguration.CopyTagsToBackups", a.ko.Spec.OpenZFSConfiguration.CopyTagsToBackups, b.ko.Spec.OpenZFSConfiguration.CopyTagsToBackups)
		} else if a.ko.Spec.OpenZFSConfiguration.CopyTagsToBackups != nil && b.ko.Spec.OpenZFSConfiguration.CopyTagsToBackups != nil {
			if *a.ko.Spec.OpenZFSConfiguration.CopyTagsToBackups != *b.ko.Spec.OpenZFSConfiguration.CopyTagsToBackups {
				delta.Add("Spec.OpenZFSConfiguration.CopyTagsToBackups", a.ko.Spec.OpenZFSConfiguration.CopyTagsToBackups, b.ko.Spec.OpenZFSConfiguration.CopyTagsToBackups)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.OpenZFSConfiguration.CopyTagsToVolumes, b.ko.Spec.OpenZFSConfiguration.CopyTagsToVolumes) {
			delta.Add("Spec.OpenZFSConfiguration.CopyTagsToVolumes", a.ko.Spec.OpenZFSConfiguration.CopyTagsToVolumes, b.ko.Spec.OpenZFSConfiguration.CopyTagsToVolumes)
		} else if a.ko.Spec.OpenZFSConfiguration.CopyTagsToVolumes != nil && b.ko.Spec.OpenZFSConfiguration.CopyTagsToVolumes != nil {
			if *a.ko.Spec.OpenZFSConfiguration.CopyTagsToVolumes != *b.ko.Spec.OpenZFSConfiguration.CopyTagsToVolumes {
				delta.Add("Spec.OpenZFSConfiguration.CopyTagsToVolumes", a.ko.Spec.OpenZFSConfiguration.CopyTagsToVolumes, b.ko.Spec.OpenZFSConfiguration.CopyTagsToVolumes)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.OpenZFSConfiguration.DailyAutomaticBackupStartTime, b.ko.Spec.OpenZFSConfiguration.DailyAutomaticBackupStartTime) {
			delta.Add("Spec.OpenZFSConfiguration.DailyAutomaticBackupStartTime", a.ko.Spec.OpenZFSConfiguration.DailyAutomaticBackupStartTime, b.ko.Spec.OpenZFSConfiguration.DailyAutomaticBackupStartTime)
		} else if a.ko.Spec.OpenZFSConfiguration.DailyAutomaticBackupStartTime != nil && b.ko.Spec.OpenZFSConfiguration.DailyAutomaticBackupStartTime != nil {
			if *a.ko.Spec.OpenZFSConfiguration.DailyAutomaticBackupStartTime != *b.ko.Spec.OpenZFSConfiguration.DailyAutomaticBackupStartTime {
				delta.Add("Spec.OpenZFSConfiguration.DailyAutomaticBackupStartTime", a.ko.Spec.OpenZFSConfiguration.DailyAutomaticBackupStartTime, b.ko.Spec.OpenZFSConfiguration.DailyAutomaticBackupStartTime)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.OpenZFSConfiguration.DeploymentType, b.ko.Spec.OpenZFSConfiguration.DeploymentType) {
			delta.Add("Spec.OpenZFSConfiguration.DeploymentType", a.ko.Spec.OpenZFSConfiguration.DeploymentType, b.ko.Spec.OpenZFSConfiguration.DeploymentType)
		} else if a.ko.Spec.OpenZFSConfiguration.DeploymentType != nil && b.ko.Spec.OpenZFSConfiguration.DeploymentType != nil {
			if *a.ko.Spec.OpenZFSConfiguration.DeploymentType != *b.ko.Spec.OpenZFSConfiguration.DeploymentType {
				delta.Add("Spec.OpenZFSConfiguration.DeploymentType", a.ko.Spec.OpenZFSConfiguration.DeploymentType, b.ko.Spec.OpenZFSConfiguration.DeploymentType)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.OpenZFSConfiguration.DiskIOPSConfiguration, b.ko.Spec.OpenZFSConfiguration.DiskIOPSConfiguration) {
			delta.Add("Spec.OpenZFSConfiguration.DiskIOPSConfiguration", a.ko.Spec.OpenZFSConfiguration.DiskIOPSConfiguration, b.ko.Spec.OpenZFSConfiguration.DiskIOPSConfiguration)
		} else if a.ko.Spec.OpenZFSConfiguration.DiskIOPSConfiguration != nil && b.ko.Spec.OpenZFSConfiguration.DiskIOPSConfiguration != nil {
			if ackcompare.HasNilDifference(a.ko.Spec.OpenZFSConfiguration.DiskIOPSConfiguration.IOPS, b.ko.Spec.OpenZFSConfiguration.DiskIOPSConfiguration.IOPS) {
				delta.Add("Spec.OpenZFSConfiguration.DiskIOPSConfiguration.IOPS", a.ko.Spec.OpenZFSConfiguration.DiskIOPSConfiguration.IOPS, b.ko.Spec.OpenZFSConfiguration.DiskIOPSConfiguration.IOPS)
			} else if a.ko.Spec.OpenZFSConfiguration.DiskIOPSConfiguration.IOPS != nil && b.ko.Spec.OpenZFSConfiguration.DiskIOPSConfiguration.IOPS != nil {
				if *a.ko.Spec.OpenZFSConfiguration.DiskIOPSConfiguration.IOPS != *b.ko.Spec.OpenZFSConfiguration.DiskIOPSConfiguration.IOPS {
					delta.Add("Spec.OpenZFSConfiguration.DiskIOPSConfiguration.IOPS", a.ko.Spec.OpenZFSConfiguration.DiskIOPSConfiguration.IOPS, b.ko.Spec.OpenZFSConfiguration.DiskIOPSConfiguration.IOPS)
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.OpenZFSConfiguration.DiskIOPSConfiguration.Mode, b.ko.Spec.OpenZFSConfiguration.DiskIOPSConfiguration.Mode) {
				delta.Add("Spec.OpenZFSConfiguration.DiskIOPSConfiguration.Mode", a.ko.Spec.OpenZFSConfiguration.DiskIOPSConfiguration.Mode, b.ko.Spec.OpenZFSConfiguration.DiskIOPSConfiguration.Mode)
			} else if a.ko.Spec.OpenZFSConfiguration.DiskIOPSConfiguration.Mode != nil && b.ko.Spec.OpenZFSConfiguration.DiskIOPSConfiguration.Mode != nil {
				if *a.ko.Spec.OpenZFSConfiguration.DiskIOPSConfiguration.Mode != *b.ko.Spec.OpenZFSConfiguration.DiskIOPSConfiguration.Mode {
					delta.Add("Spec.OpenZFSConfiguration.DiskIOPSConfiguration.Mode", a.ko.Spec.OpenZFSConfiguration.DiskIOPSConfiguration.Mode, b.ko.Spec.OpenZFSConfiguration.DiskIOPSConfiguration.Mode)
				}
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.OpenZFSConfiguration.EndpointIPAddressRange, b.ko.Spec.OpenZFSConfiguration.EndpointIPAddressRange) {
			delta.Add("Spec.OpenZFSConfiguration.EndpointIPAddressRange", a.ko.Spec.OpenZFSConfiguration.EndpointIPAddressRange, b.ko.Spec.OpenZFSConfiguration.EndpointIPAddressRange)
		} else if a.ko.Spec.OpenZFSConfiguration.EndpointIPAddressRange != nil && b.ko.Spec.OpenZFSConfiguration.EndpointIPAddressRange != nil {
			if *a.ko.Spec.OpenZFSConfiguration.EndpointIPAddressRange != *b.ko.Spec.OpenZFSConfiguration.EndpointIPAddressRange {
				delta.Add("Spec.OpenZFSConfiguration.EndpointIPAddressRange", a.ko.Spec.OpenZFSConfiguration.EndpointIPAddressRange, b.ko.Spec.OpenZFSConfiguration.EndpointIPAddressRange)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.OpenZFSConfiguration.EndpointIPv6AddressRange, b.ko.Spec.OpenZFSConfiguration.EndpointIPv6AddressRange) {
			delta.Add("Spec.OpenZFSConfiguration.EndpointIPv6AddressRange", a.ko.Spec.OpenZFSConfiguration.EndpointIPv6AddressRange, b.ko.Spec.OpenZFSConfiguration.EndpointIPv6AddressRange)
		} else if a.ko.Spec.OpenZFSConfiguration.EndpointIPv6AddressRange != nil && b.ko.Spec.OpenZFSConfiguration.EndpointIPv6AddressRange != nil {
			if *a.ko.Spec.OpenZFSConfiguration.EndpointIPv6AddressRange != *b.ko.Spec.OpenZFSConfiguration.EndpointIPv6AddressRange {
				delta.Add("Spec.OpenZFSConfiguration.EndpointIPv6AddressRange", a.ko.Spec.OpenZFSConfiguration.EndpointIPv6AddressRange, b.ko.Spec.OpenZFSConfiguration.EndpointIPv6AddressRange)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.OpenZFSConfiguration.PreferredSubnetID, b.ko.Spec.OpenZFSConfiguration.PreferredSubnetID) {
			delta.Add("Spec.OpenZFSConfiguration.PreferredSubnetID", a.ko.Spec.OpenZFSConfiguration.PreferredSubnetID, b.ko.Spec.OpenZFSConfiguration.PreferredSubnetID)
		} else if a.ko.Spec.OpenZFSConfiguration.PreferredSubnetID != nil && b.ko.Spec.OpenZFSConfiguration.PreferredSubnetID != nil {
			if *a.ko.Spec.OpenZFSConfiguration.PreferredSubnetID != *b.ko.Spec.OpenZFSConfiguration.PreferredSubnetID {
				delta.Add("Spec.OpenZFSConfiguration.PreferredSubnetID", a.ko.Spec.OpenZFSConfiguration.PreferredSubnetID, b.ko.Spec.OpenZFSConfiguration.PreferredSubnetID)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.OpenZFSConfiguration.ReadCacheConfiguration, b.ko.Spec.OpenZFSConfiguration.ReadCacheConfiguration) {
			delta.Add("Spec.OpenZFSConfiguration.ReadCacheConfiguration", a.ko.Spec.OpenZFSConfiguration.ReadCacheConfiguration, b.ko.Spec.OpenZFSConfiguration.ReadCacheConfiguration)
		} else if a.ko.Spec.OpenZFSConfiguration.ReadCacheConfiguration != nil && b.ko.Spec.OpenZFSConfiguration.ReadCacheConfiguration != nil {
			if ackcompare.HasNilDifference(a.ko.Spec.OpenZFSConfiguration.ReadCacheConfiguration.SizeGiB, b.ko.Spec.OpenZFSConfiguration.ReadCacheConfiguration.SizeGiB) {
				delta.Add("Spec.OpenZFSConfiguration.ReadCacheConfiguration.SizeGiB", a.ko.Spec.OpenZFSConfiguration.ReadCacheConfiguration.SizeGiB, b.ko.Spec.OpenZFSConfiguration.ReadCacheConfiguration.SizeGiB)
			} else if a.ko.Spec.OpenZFSConfiguration.ReadCacheConfiguration.SizeGiB != nil && b.ko.Spec.OpenZFSConfiguration.ReadCacheConfiguration.SizeGiB != nil {
				if *a.ko.Spec.OpenZFSConfiguration.ReadCacheConfiguration.SizeGiB != *b.ko.Spec.OpenZFSConfiguration.ReadCacheConfiguration.SizeGiB {
					delta.Add("Spec.OpenZFSConfiguration.ReadCacheConfiguration.SizeGiB", a.ko.Spec.OpenZFSConfiguration.ReadCacheConfiguration.SizeGiB, b.ko.Spec.OpenZFSConfiguration.ReadCacheConfiguration.SizeGiB)
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.OpenZFSConfiguration.ReadCacheConfiguration.SizingMode, b.ko.Spec.OpenZFSConfiguration.ReadCacheConfiguration.SizingMode) {
				delta.Add("Spec.OpenZFSConfiguration.ReadCacheConfiguration.SizingMode", a.ko.Spec.OpenZFSConfiguration.ReadCacheConfiguration.SizingMode, b.ko.Spec.OpenZFSConfiguration.ReadCacheConfiguration.SizingMode)
			} else if a.ko.Spec.OpenZFSConfiguration.ReadCacheConfiguration.SizingMode != nil && b.ko.Spec.OpenZFSConfiguration.ReadCacheConfiguration.SizingMode != nil {
				if *a.ko.Spec.OpenZFSConfiguration.ReadCacheConfiguration.SizingMode != *b.ko.Spec.OpenZFSConfiguration.ReadCacheConfiguration.SizingMode {
					delta.Add("Spec.OpenZFSConfiguration.ReadCacheConfiguration.SizingMode", a.ko.Spec.OpenZFSConfiguration.ReadCacheConfiguration.SizingMode, b.ko.Spec.OpenZFSConfiguration.ReadCacheConfiguration.SizingMode)
				}
			}
		}
		if len(a.ko.Spec.OpenZFSConfiguration.RouteTableIDs) != len(b.ko.Spec.OpenZFSConfiguration.RouteTableIDs) {
			delta.Add("Spec.OpenZFSConfiguration.RouteTableIDs", a.ko.Spec.OpenZFSConfiguration.RouteTableIDs, b.ko.Spec.OpenZFSConfiguration.RouteTableIDs)
		} else if len(a.ko.Spec.OpenZFSConfiguration.RouteTableIDs) > 0 {
			if !ackcompare.SliceStringPEqual(a.ko.Spec.OpenZFSConfiguration.RouteTableIDs, b.ko.Spec.OpenZFSConfiguration.RouteTableIDs) {
				delta.Add("Spec.OpenZFSConfiguration.RouteTableIDs", a.ko.Spec.OpenZFSConfiguration.RouteTableIDs, b.ko.Spec.OpenZFSConfiguration.RouteTableIDs)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.OpenZFSConfiguration.ThroughputCapacity, b.ko.Spec.OpenZFSConfiguration.ThroughputCapacity) {
			delta.Add("Spec.OpenZFSConfiguration.ThroughputCapacity", a.ko.Spec.OpenZFSConfiguration.ThroughputCapacity, b.ko.Spec.OpenZFSConfiguration.ThroughputCapacity)
		} else if a.ko.Spec.OpenZFSConfiguration.ThroughputCapacity != nil && b.ko.Spec.OpenZFSConfiguration.ThroughputCapacity != nil {
			if *a.ko.Spec.OpenZFSConfiguration.ThroughputCapacity != *b.ko.Spec.OpenZFSConfiguration.ThroughputCapacity {
				delta.Add("Spec.OpenZFSConfiguration.ThroughputCapacity", a.ko.Spec.OpenZFSConfiguration.ThroughputCapacity, b.ko.Spec.OpenZFSConfiguration.ThroughputCapacity)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.OpenZFSConfiguration.WeeklyMaintenanceStartTime, b.ko.Spec.OpenZFSConfiguration.WeeklyMaintenanceStartTime) {
			delta.Add("Spec.OpenZFSConfiguration.WeeklyMaintenanceStartTime", a.ko.Spec.OpenZFSConfiguration.WeeklyMaintenanceStartTime, b.ko.Spec.OpenZFSConfiguration.WeeklyMaintenanceStartTime)
		} else if a.ko.Spec.OpenZFSConfiguration.WeeklyMaintenanceStartTime != nil && b.ko.Spec.OpenZFSConfiguration.WeeklyMaintenanceStartTime != nil {
			if *a.ko.Spec.OpenZFSConfiguration.WeeklyMaintenanceStartTime != *b.ko.Spec.OpenZFSConfiguration.WeeklyMaintenanceStartTime {
				delta.Add("Spec.OpenZFSConfiguration.WeeklyMaintenanceStartTime", a.ko.Spec.OpenZFSConfiguration.WeeklyMaintenanceStartTime, b.ko.Spec.OpenZFSConfiguration.WeeklyMaintenanceStartTime)
			}
		}
	}
	if len(a.ko.Spec.SecurityGroupIDs) != len(b.ko.Spec.SecurityGroupIDs) {
		delta.Add("Spec.SecurityGroupIDs", a.ko.Spec.SecurityGroupIDs, b.ko.Spec.SecurityGroupIDs)
	} else if len(a.ko.Spec.SecurityGroupIDs) > 0 {
		if !ackcompare.SliceStringPEqual(a.ko.Spec.SecurityGroupIDs, b.ko.Spec.SecurityGroupIDs) {
			delta.Add("Spec.SecurityGroupIDs", a.ko.Spec.SecurityGroupIDs, b.ko.Spec.SecurityGroupIDs)
		}
	}
	if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.SecurityGroupRefs, b.ko.Spec.SecurityGroupRefs) {
		delta.Add("Spec.SecurityGroupRefs", a.ko.Spec.SecurityGroupRefs, b.ko.Spec.SecurityGroupRefs)
	}
	if ackcompare.HasNilDifference(a.ko.Spec.StorageCapacity, b.ko.Spec.StorageCapacity) {
		delta.Add("Spec.StorageCapacity", a.ko.Spec.StorageCapacity, b.ko.Spec.StorageCapacity)
	} else if a.ko.Spec.StorageCapacity != nil && b.ko.Spec.StorageCapacity != nil {
		if *a.ko.Spec.StorageCapacity != *b.ko.Spec.StorageCapacity {
			delta.Add("Spec.StorageCapacity", a.ko.Spec.StorageCapacity, b.ko.Spec.StorageCapacity)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.StorageType, b.ko.Spec.StorageType) {
		delta.Add("Spec.StorageType", a.ko.Spec.StorageType, b.ko.Spec.StorageType)
	} else if a.ko.Spec.StorageType != nil && b.ko.Spec.StorageType != nil {
		if *a.ko.Spec.StorageType != *b.ko.Spec.StorageType {
			delta.Add("Spec.StorageType", a.ko.Spec.StorageType, b.ko.Spec.StorageType)
		}
	}
	if len(a.ko.Spec.SubnetIDs) != len(b.ko.Spec.SubnetIDs) {
		delta.Add("Spec.SubnetIDs", a.ko.Spec.SubnetIDs, b.ko.Spec.SubnetIDs)
	} else if len(a.ko.Spec.SubnetIDs) > 0 {
		if !ackcompare.SliceStringPEqual(a.ko.Spec.SubnetIDs, b.ko.Spec.SubnetIDs) {
			delta.Add("Spec.SubnetIDs", a.ko.Spec.SubnetIDs, b.ko.Spec.SubnetIDs)
		}
	}
	if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.SubnetRefs, b.ko.Spec.SubnetRefs) {
		delta.Add("Spec.SubnetRefs", a.ko.Spec.SubnetRefs, b.ko.Spec.SubnetRefs)
	}
	desiredACKTags, _ := convertToOrderedACKTags(a.ko.Spec.Tags)
	latestACKTags, _ := convertToOrderedACKTags(b.ko.Spec.Tags)
	if !ackcompare.MapStringStringEqual(desiredACKTags, latestACKTags) {
		delta.Add("Spec.Tags", a.ko.Spec.Tags, b.ko.Spec.Tags)
	}
	if ackcompare.HasNilDifference(a.ko.Spec.WindowsConfiguration, b.ko.Spec.WindowsConfiguration) {
		delta.Add("Spec.WindowsConfiguration", a.ko.Spec.WindowsConfiguration, b.ko.Spec.WindowsConfiguration)
	} else if a.ko.Spec.WindowsConfiguration != nil && b.ko.Spec.WindowsConfiguration != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.WindowsConfiguration.ActiveDirectoryID, b.ko.Spec.WindowsConfiguration.ActiveDirectoryID) {
			delta.Add("Spec.WindowsConfiguration.ActiveDirectoryID", a.ko.Spec.WindowsConfiguration.ActiveDirectoryID, b.ko.Spec.WindowsConfiguration.ActiveDirectoryID)
		} else if a.ko.Spec.WindowsConfiguration.ActiveDirectoryID != nil && b.ko.Spec.WindowsConfiguration.ActiveDirectoryID != nil {
			if *a.ko.Spec.WindowsConfiguration.ActiveDirectoryID != *b.ko.Spec.WindowsConfiguration.ActiveDirectoryID {
				delta.Add("Spec.WindowsConfiguration.ActiveDirectoryID", a.ko.Spec.WindowsConfiguration.ActiveDirectoryID, b.ko.Spec.WindowsConfiguration.ActiveDirectoryID)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.WindowsConfiguration.AuditLogConfiguration, b.ko.Spec.WindowsConfiguration.AuditLogConfiguration) {
			delta.Add("Spec.WindowsConfiguration.AuditLogConfiguration", a.ko.Spec.WindowsConfiguration.AuditLogConfiguration, b.ko.Spec.WindowsConfiguration.AuditLogConfiguration)
		} else if a.ko.Spec.WindowsConfiguration.AuditLogConfiguration != nil && b.ko.Spec.WindowsConfiguration.AuditLogConfiguration != nil {
			if ackcompare.HasNilDifference(a.ko.Spec.WindowsConfiguration.AuditLogConfiguration.AuditLogDestination, b.ko.Spec.WindowsConfiguration.AuditLogConfiguration.AuditLogDestination) {
				delta.Add("Spec.WindowsConfiguration.AuditLogConfiguration.AuditLogDestination", a.ko.Spec.WindowsConfiguration.AuditLogConfiguration.AuditLogDestination, b.ko.Spec.WindowsConfiguration.AuditLogConfiguration.AuditLogDestination)
			} else if a.ko.Spec.WindowsConfiguration.AuditLogConfiguration.AuditLogDestination != nil && b.ko.Spec.WindowsConfiguration.AuditLogConfiguration.AuditLogDestination != nil {
				if *a.ko.Spec.WindowsConfiguration.AuditLogConfiguration.AuditLogDestination != *b.ko.Spec.WindowsConfiguration.AuditLogConfiguration.AuditLogDestination {
					delta.Add("Spec.WindowsConfiguration.AuditLogConfiguration.AuditLogDestination", a.ko.Spec.WindowsConfiguration.AuditLogConfiguration.AuditLogDestination, b.ko.Spec.WindowsConfiguration.AuditLogConfiguration.AuditLogDestination)
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.WindowsConfiguration.AuditLogConfiguration.FileAccessAuditLogLevel, b.ko.Spec.WindowsConfiguration.AuditLogConfiguration.FileAccessAuditLogLevel) {
				delta.Add("Spec.WindowsConfiguration.AuditLogConfiguration.FileAccessAuditLogLevel", a.ko.Spec.WindowsConfiguration.AuditLogConfiguration.FileAccessAuditLogLevel, b.ko.Spec.WindowsConfiguration.AuditLogConfiguration.FileAccessAuditLogLevel)
			} else if a.ko.Spec.WindowsConfiguration.AuditLogConfiguration.FileAccessAuditLogLevel != nil && b.ko.Spec.WindowsConfiguration.AuditLogConfiguration.FileAccessAuditLogLevel != nil {
				if *a.ko.Spec.WindowsConfiguration.AuditLogConfiguration.FileAccessAuditLogLevel != *b.ko.Spec.WindowsConfiguration.AuditLogConfiguration.FileAccessAuditLogLevel {
					delta.Add("Spec.WindowsConfiguration.AuditLogConfiguration.FileAccessAuditLogLevel", a.ko.Spec.WindowsConfiguration.AuditLogConfiguration.FileAccessAuditLogLevel, b.ko.Spec.WindowsConfiguration.AuditLogConfiguration.FileAccessAuditLogLevel)
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.WindowsConfiguration.AuditLogConfiguration.FileShareAccessAuditLogLevel, b.ko.Spec.WindowsConfiguration.AuditLogConfiguration.FileShareAccessAuditLogLevel) {
				delta.Add("Spec.WindowsConfiguration.AuditLogConfiguration.FileShareAccessAuditLogLevel", a.ko.Spec.WindowsConfiguration.AuditLogConfiguration.FileShareAccessAuditLogLevel, b.ko.Spec.WindowsConfiguration.AuditLogConfiguration.FileShareAccessAuditLogLevel)
			} else if a.ko.Spec.WindowsConfiguration.AuditLogConfiguration.FileShareAccessAuditLogLevel != nil && b.ko.Spec.WindowsConfiguration.AuditLogConfiguration.FileShareAccessAuditLogLevel != nil {
				if *a.ko.Spec.WindowsConfiguration.AuditLogConfiguration.FileShareAccessAuditLogLevel != *b.ko.Spec.WindowsConfiguration.AuditLogConfiguration.FileShareAccessAuditLogLevel {
					delta.Add("Spec.WindowsConfiguration.AuditLogConfiguration.FileShareAccessAuditLogLevel", a.ko.Spec.WindowsConfiguration.AuditLogConfiguration.FileShareAccessAuditLogLevel, b.ko.Spec.WindowsConfiguration.AuditLogConfiguration.FileShareAccessAuditLogLevel)
				}
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.WindowsConfiguration.AutomaticBackupRetentionDays, b.ko.Spec.WindowsConfiguration.AutomaticBackupRetentionDays) {
			delta.Add("Spec.WindowsConfiguration.AutomaticBackupRetentionDays", a.ko.Spec.WindowsConfiguration.AutomaticBackupRetentionDays, b.ko.Spec.WindowsConfiguration.AutomaticBackupRetentionDays)
		} else if a.ko.Spec.WindowsConfiguration.AutomaticBackupRetentionDays != nil && b.ko.Spec.WindowsConfiguration.AutomaticBackupRetentionDays != nil {
			if *a.ko.Spec.WindowsConfiguration.AutomaticBackupRetentionDays != *b.ko.Spec.WindowsConfiguration.AutomaticBackupRetentionDays {
				delta.Add("Spec.WindowsConfiguration.AutomaticBackupRetentionDays", a.ko.Spec.WindowsConfiguration.AutomaticBackupRetentionDays, b.ko.Spec.WindowsConfiguration.AutomaticBackupRetentionDays)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.WindowsConfiguration.CopyTagsToBackups, b.ko.Spec.WindowsConfiguration.CopyTagsToBackups) {
			delta.Add("Spec.WindowsConfiguration.CopyTagsToBackups", a.ko.Spec.WindowsConfiguration.CopyTagsToBackups, b.ko.Spec.WindowsConfiguration.CopyTagsToBackups)
		} else if a.ko.Spec.WindowsConfiguration.CopyTagsToBackups != nil && b.ko.Spec.WindowsConfiguration.CopyTagsToBackups != nil {
			if *a.ko.Spec.WindowsConfiguration.CopyTagsToBackups != *b.ko.Spec.WindowsConfiguration.CopyTagsToBackups {
				delta.Add("Spec.WindowsConfiguration.CopyTagsToBackups", a.ko.Spec.WindowsConfiguration.CopyTagsToBackups, b.ko.Spec.WindowsConfiguration.CopyTagsToBackups)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.WindowsConfiguration.DailyAutomaticBackupStartTime, b.ko.Spec.WindowsConfiguration.DailyAutomaticBackupStartTime) {
			delta.Add("Spec.WindowsConfiguration.DailyAutomaticBackupStartTime", a.ko.Spec.WindowsConfiguration.DailyAutomaticBackupStartTime, b.ko.Spec.WindowsConfiguration.DailyAutomaticBackupStartTime)
		} else if a.ko.Spec.WindowsConfiguration.DailyAutomaticBackupStartTime != nil && b.ko.Spec.WindowsConfiguration.DailyAutomaticBackupStartTime != nil {
			if *a.ko.Spec.WindowsConfiguration.DailyAutomaticBackupStartTime != *b.ko.Spec.WindowsConfiguration.DailyAutomaticBackupStartTime {
				delta.Add("Spec.WindowsConfiguration.DailyAutomaticBackupStartTime", a.ko.Spec.WindowsConfiguration.DailyAutomaticBackupStartTime, b.ko.Spec.WindowsConfiguration.DailyAutomaticBackupStartTime)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.WindowsConfiguration.DeploymentType, b.ko.Spec.WindowsConfiguration.DeploymentType) {
			delta.Add("Spec.WindowsConfiguration.DeploymentType", a.ko.Spec.WindowsConfiguration.DeploymentType, b.ko.Spec.WindowsConfiguration.DeploymentType)
		} else if a.ko.Spec.WindowsConfiguration.DeploymentType != nil && b.ko.Spec.WindowsConfiguration.DeploymentType != nil {
			if *a.ko.Spec.WindowsConfiguration.DeploymentType != *b.ko.Spec.WindowsConfiguration.DeploymentType {
				delta.Add("Spec.WindowsConfiguration.DeploymentType", a.ko.Spec.WindowsConfiguration.DeploymentType, b.ko.Spec.WindowsConfiguration.DeploymentType)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.WindowsConfiguration.DiskIOPSConfiguration, b.ko.Spec.WindowsConfiguration.DiskIOPSConfiguration) {
			delta.Add("Spec.WindowsConfiguration.DiskIOPSConfiguration", a.ko.Spec.WindowsConfiguration.DiskIOPSConfiguration, b.ko.Spec.WindowsConfiguration.DiskIOPSConfiguration)
		} else if a.ko.Spec.WindowsConfiguration.DiskIOPSConfiguration != nil && b.ko.Spec.WindowsConfiguration.DiskIOPSConfiguration != nil {
			if ackcompare.HasNilDifference(a.ko.Spec.WindowsConfiguration.DiskIOPSConfiguration.IOPS, b.ko.Spec.WindowsConfiguration.DiskIOPSConfiguration.IOPS) {
				delta.Add("Spec.WindowsConfiguration.DiskIOPSConfiguration.IOPS", a.ko.Spec.WindowsConfiguration.DiskIOPSConfiguration.IOPS, b.ko.Spec.WindowsConfiguration.DiskIOPSConfiguration.IOPS)
			} else if a.ko.Spec.WindowsConfiguration.DiskIOPSConfiguration.IOPS != nil && b.ko.Spec.WindowsConfiguration.DiskIOPSConfiguration.IOPS != nil {
				if *a.ko.Spec.WindowsConfiguration.DiskIOPSConfiguration.IOPS != *b.ko.Spec.WindowsConfiguration.DiskIOPSConfiguration.IOPS {
					delta.Add("Spec.WindowsConfiguration.DiskIOPSConfiguration.IOPS", a.ko.Spec.WindowsConfiguration.DiskIOPSConfiguration.IOPS, b.ko.Spec.WindowsConfiguration.DiskIOPSConfiguration.IOPS)
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.WindowsConfiguration.DiskIOPSConfiguration.Mode, b.ko.Spec.WindowsConfiguration.DiskIOPSConfiguration.Mode) {
				delta.Add("Spec.WindowsConfiguration.DiskIOPSConfiguration.Mode", a.ko.Spec.WindowsConfiguration.DiskIOPSConfiguration.Mode, b.ko.Spec.WindowsConfiguration.DiskIOPSConfiguration.Mode)
			} else if a.ko.Spec.WindowsConfiguration.DiskIOPSConfiguration.Mode != nil && b.ko.Spec.WindowsConfiguration.DiskIOPSConfiguration.Mode != nil {
				if *a.ko.Spec.WindowsConfiguration.DiskIOPSConfiguration.Mode != *b.ko.Spec.WindowsConfiguration.DiskIOPSConfiguration.Mode {
					delta.Add("Spec.WindowsConfiguration.DiskIOPSConfiguration.Mode", a.ko.Spec.WindowsConfiguration.DiskIOPSConfiguration.Mode, b.ko.Spec.WindowsConfiguration.DiskIOPSConfiguration.Mode)
				}
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.WindowsConfiguration.FsrmConfiguration, b.ko.Spec.WindowsConfiguration.FsrmConfiguration) {
			delta.Add("Spec.WindowsConfiguration.FsrmConfiguration", a.ko.Spec.WindowsConfiguration.FsrmConfiguration, b.ko.Spec.WindowsConfiguration.FsrmConfiguration)
		} else if a.ko.Spec.WindowsConfiguration.FsrmConfiguration != nil && b.ko.Spec.WindowsConfiguration.FsrmConfiguration != nil {
			if ackcompare.HasNilDifference(a.ko.Spec.WindowsConfiguration.FsrmConfiguration.EventLogDestination, b.ko.Spec.WindowsConfiguration.FsrmConfiguration.EventLogDestination) {
				delta.Add("Spec.WindowsConfiguration.FsrmConfiguration.EventLogDestination", a.ko.Spec.WindowsConfiguration.FsrmConfiguration.EventLogDestination, b.ko.Spec.WindowsConfiguration.FsrmConfiguration.EventLogDestination)
			} else if a.ko.Spec.WindowsConfiguration.FsrmConfiguration.EventLogDestination != nil && b.ko.Spec.WindowsConfiguration.FsrmConfiguration.EventLogDestination != nil {
				if *a.ko.Spec.WindowsConfiguration.FsrmConfiguration.EventLogDestination != *b.ko.Spec.WindowsConfiguration.FsrmConfiguration.EventLogDestination {
					delta.Add("Spec.WindowsConfiguration.FsrmConfiguration.EventLogDestination", a.ko.Spec.WindowsConfiguration.FsrmConfiguration.EventLogDestination, b.ko.Spec.WindowsConfiguration.FsrmConfiguration.EventLogDestination)
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.WindowsConfiguration.FsrmConfiguration.FsrmServiceEnabled, b.ko.Spec.WindowsConfiguration.FsrmConfiguration.FsrmServiceEnabled) {
				delta.Add("Spec.WindowsConfiguration.FsrmConfiguration.FsrmServiceEnabled", a.ko.Spec.WindowsConfiguration.FsrmConfiguration.FsrmServiceEnabled, b.ko.Spec.WindowsConfiguration.FsrmConfiguration.FsrmServiceEnabled)
			} else if a.ko.Spec.WindowsConfiguration.FsrmConfiguration.FsrmServiceEnabled != nil && b.ko.Spec.WindowsConfiguration.FsrmConfiguration.FsrmServiceEnabled != nil {
				if *a.ko.Spec.WindowsConfiguration.FsrmConfiguration.FsrmServiceEnabled != *b.ko.Spec.WindowsConfiguration.FsrmConfiguration.FsrmServiceEnabled {
					delta.Add("Spec.WindowsConfiguration.FsrmConfiguration.FsrmServiceEnabled", a.ko.Spec.WindowsConfiguration.FsrmConfiguration.FsrmServiceEnabled, b.ko.Spec.WindowsConfiguration.FsrmConfiguration.FsrmServiceEnabled)
				}
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.WindowsConfiguration.PreferredSubnetID, b.ko.Spec.WindowsConfiguration.PreferredSubnetID) {
			delta.Add("Spec.WindowsConfiguration.PreferredSubnetID", a.ko.Spec.WindowsConfiguration.PreferredSubnetID, b.ko.Spec.WindowsConfiguration.PreferredSubnetID)
		} else if a.ko.Spec.WindowsConfiguration.PreferredSubnetID != nil && b.ko.Spec.WindowsConfiguration.PreferredSubnetID != nil {
			if *a.ko.Spec.WindowsConfiguration.PreferredSubnetID != *b.ko.Spec.WindowsConfiguration.PreferredSubnetID {
				delta.Add("Spec.WindowsConfiguration.PreferredSubnetID", a.ko.Spec.WindowsConfiguration.PreferredSubnetID, b.ko.Spec.WindowsConfiguration.PreferredSubnetID)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration, b.ko.Spec.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration) {
			delta.Add("Spec.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration", a.ko.Spec.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration, b.ko.Spec.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration)
		} else if a.ko.Spec.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration != nil && b.ko.Spec.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration != nil {
			if len(a.ko.Spec.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.DNSIPs) != len(b.ko.Spec.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.DNSIPs) {
				delta.Add("Spec.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.DNSIPs", a.ko.Spec.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.DNSIPs, b.ko.Spec.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.DNSIPs)
			} else if len(a.ko.Spec.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.DNSIPs) > 0 {
				if !ackcompare.SliceStringPEqual(a.ko.Spec.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.DNSIPs, b.ko.Spec.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.DNSIPs) {
					delta.Add("Spec.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.DNSIPs", a.ko.Spec.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.DNSIPs, b.ko.Spec.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.DNSIPs)
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.DomainJoinServiceAccountSecret, b.ko.Spec.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.DomainJoinServiceAccountSecret) {
				delta.Add("Spec.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.DomainJoinServiceAccountSecret", a.ko.Spec.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.DomainJoinServiceAccountSecret, b.ko.Spec.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.DomainJoinServiceAccountSecret)
			} else if a.ko.Spec.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.DomainJoinServiceAccountSecret != nil && b.ko.Spec.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.DomainJoinServiceAccountSecret != nil {
				if *a.ko.Spec.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.DomainJoinServiceAccountSecret != *b.ko.Spec.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.DomainJoinServiceAccountSecret {
					delta.Add("Spec.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.DomainJoinServiceAccountSecret", a.ko.Spec.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.DomainJoinServiceAccountSecret, b.ko.Spec.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.DomainJoinServiceAccountSecret)
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.DomainName, b.ko.Spec.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.DomainName) {
				delta.Add("Spec.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.DomainName", a.ko.Spec.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.DomainName, b.ko.Spec.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.DomainName)
			} else if a.ko.Spec.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.DomainName != nil && b.ko.Spec.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.DomainName != nil {
				if *a.ko.Spec.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.DomainName != *b.ko.Spec.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.DomainName {
					delta.Add("Spec.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.DomainName", a.ko.Spec.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.DomainName, b.ko.Spec.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.DomainName)
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.FileSystemAdministratorsGroup, b.ko.Spec.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.FileSystemAdministratorsGroup) {
				delta.Add("Spec.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.FileSystemAdministratorsGroup", a.ko.Spec.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.FileSystemAdministratorsGroup, b.ko.Spec.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.FileSystemAdministratorsGroup)
			} else if a.ko.Spec.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.FileSystemAdministratorsGroup != nil && b.ko.Spec.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.FileSystemAdministratorsGroup != nil {
				if *a.ko.Spec.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.FileSystemAdministratorsGroup != *b.ko.Spec.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.FileSystemAdministratorsGroup {
					delta.Add("Spec.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.FileSystemAdministratorsGroup", a.ko.Spec.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.FileSystemAdministratorsGroup, b.ko.Spec.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.FileSystemAdministratorsGroup)
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.OrganizationalUnitDistinguishedName, b.ko.Spec.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.OrganizationalUnitDistinguishedName) {
				delta.Add("Spec.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.OrganizationalUnitDistinguishedName", a.ko.Spec.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.OrganizationalUnitDistinguishedName, b.ko.Spec.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.OrganizationalUnitDistinguishedName)
			} else if a.ko.Spec.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.OrganizationalUnitDistinguishedName != nil && b.ko.Spec.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.OrganizationalUnitDistinguishedName != nil {
				if *a.ko.Spec.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.OrganizationalUnitDistinguishedName != *b.ko.Spec.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.OrganizationalUnitDistinguishedName {
					delta.Add("Spec.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.OrganizationalUnitDistinguishedName", a.ko.Spec.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.OrganizationalUnitDistinguishedName, b.ko.Spec.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.OrganizationalUnitDistinguishedName)
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.UserName, b.ko.Spec.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.UserName) {
				delta.Add("Spec.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.UserName", a.ko.Spec.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.UserName, b.ko.Spec.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.UserName)
			} else if a.ko.Spec.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.UserName != nil && b.ko.Spec.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.UserName != nil {
				if *a.ko.Spec.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.UserName != *b.ko.Spec.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.UserName {
					delta.Add("Spec.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.UserName", a.ko.Spec.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.UserName, b.ko.Spec.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.UserName)
				}
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.WindowsConfiguration.ThroughputCapacity, b.ko.Spec.WindowsConfiguration.ThroughputCapacity) {
			delta.Add("Spec.WindowsConfiguration.ThroughputCapacity", a.ko.Spec.WindowsConfiguration.ThroughputCapacity, b.ko.Spec.WindowsConfiguration.ThroughputCapacity)
		} else if a.ko.Spec.WindowsConfiguration.ThroughputCapacity != nil && b.ko.Spec.WindowsConfiguration.ThroughputCapacity != nil {
			if *a.ko.Spec.WindowsConfiguration.ThroughputCapacity != *b.ko.Spec.WindowsConfiguration.ThroughputCapacity {
				delta.Add("Spec.WindowsConfiguration.ThroughputCapacity", a.ko.Spec.WindowsConfiguration.ThroughputCapacity, b.ko.Spec.WindowsConfiguration.ThroughputCapacity)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.WindowsConfiguration.WeeklyMaintenanceStartTime, b.ko.Spec.WindowsConfiguration.WeeklyMaintenanceStartTime) {
			delta.Add("Spec.WindowsConfiguration.WeeklyMaintenanceStartTime", a.ko.Spec.WindowsConfiguration.WeeklyMaintenanceStartTime, b.ko.Spec.WindowsConfiguration.WeeklyMaintenanceStartTime)
		} else if a.ko.Spec.WindowsConfiguration.WeeklyMaintenanceStartTime != nil && b.ko.Spec.WindowsConfiguration.WeeklyMaintenanceStartTime != nil {
			if *a.ko.Spec.WindowsConfiguration.WeeklyMaintenanceStartTime != *b.ko.Spec.WindowsConfiguration.WeeklyMaintenanceStartTime {
				delta.Add("Spec.WindowsConfiguration.WeeklyMaintenanceStartTime", a.ko.Spec.WindowsConfiguration.WeeklyMaintenanceStartTime, b.ko.Spec.WindowsConfiguration.WeeklyMaintenanceStartTime)
			}
		}
	}

	return delta
}
