// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package file_system

import (
	"context"
	"errors"
	"fmt"
	"math"
	"reflect"
	"strings"

	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	ackcondition "github.com/aws-controllers-k8s/runtime/pkg/condition"
	ackerr "github.com/aws-controllers-k8s/runtime/pkg/errors"
	ackrequeue "github.com/aws-controllers-k8s/runtime/pkg/requeue"
	ackrtlog "github.com/aws-controllers-k8s/runtime/pkg/runtime/log"
	"github.com/aws/aws-sdk-go-v2/aws"
	svcsdk "github.com/aws/aws-sdk-go-v2/service/fsx"
	svcsdktypes "github.com/aws/aws-sdk-go-v2/service/fsx/types"
	smithy "github.com/aws/smithy-go"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	svcapitypes "github.com/aws-controllers-k8s/fsx-controller/apis/v1alpha1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = strings.ToLower("")
	_ = &svcsdk.Client{}
	_ = &svcapitypes.FileSystem{}
	_ = ackv1alpha1.AWSAccountID("")
	_ = &ackerr.NotFound
	_ = &ackcondition.NotManagedMessage
	_ = &reflect.Value{}
	_ = fmt.Sprintf("")
	_ = &ackrequeue.NoRequeue{}
	_ = &aws.Config{}
)

// sdkFind returns SDK-specific information about a supplied resource
func (rm *resourceManager) sdkFind(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkFind")
	defer func() {
		exit(err)
	}()
	// If any required fields in the input shape are missing, AWS resource is
	// not created yet. Return NotFound here to indicate to callers that the
	// resource isn't yet created.
	if rm.requiredFieldsMissingFromReadManyInput(r) {
		return nil, ackerr.NotFound
	}

	input, err := rm.newListRequestPayload(r)
	if err != nil {
		return nil, err
	}
	var resp *svcsdk.DescribeFileSystemsOutput
	resp, err = rm.sdkapi.DescribeFileSystems(ctx, input)
	rm.metrics.RecordAPICall("READ_MANY", "DescribeFileSystems", err)
	if err != nil {
		var awsErr smithy.APIError
		if errors.As(err, &awsErr) && awsErr.ErrorCode() == "FileSystemNotFound" {
			return nil, ackerr.NotFound
		}
		return nil, err
	}

	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := r.ko.DeepCopy()

	found := false
	for _, elem := range resp.FileSystems {
		if elem.CreationTime != nil {
			ko.Status.CreationTime = &metav1.Time{*elem.CreationTime}
		} else {
			ko.Status.CreationTime = nil
		}
		if elem.DNSName != nil {
			ko.Status.DNSName = elem.DNSName
		} else {
			ko.Status.DNSName = nil
		}
		if elem.FailureDetails != nil {
			f2 := &svcapitypes.FileSystemFailureDetails{}
			if elem.FailureDetails.Message != nil {
				f2.Message = elem.FailureDetails.Message
			}
			ko.Status.FailureDetails = f2
		} else {
			ko.Status.FailureDetails = nil
		}
		if elem.FileSystemId != nil {
			ko.Status.FileSystemID = elem.FileSystemId
		} else {
			ko.Status.FileSystemID = nil
		}
		if elem.FileSystemType != "" {
			ko.Spec.FileSystemType = aws.String(string(elem.FileSystemType))
		} else {
			ko.Spec.FileSystemType = nil
		}
		if elem.FileSystemTypeVersion != nil {
			ko.Spec.FileSystemTypeVersion = elem.FileSystemTypeVersion
		} else {
			ko.Spec.FileSystemTypeVersion = nil
		}
		if elem.KmsKeyId != nil {
			ko.Spec.KMSKeyID = elem.KmsKeyId
		} else {
			ko.Spec.KMSKeyID = nil
		}
		if elem.Lifecycle != "" {
			ko.Status.Lifecycle = aws.String(string(elem.Lifecycle))
		} else {
			ko.Status.Lifecycle = nil
		}
		if elem.LustreConfiguration != nil {
			f8 := &svcapitypes.CreateFileSystemLustreConfiguration{}
			if elem.LustreConfiguration.AutomaticBackupRetentionDays != nil {
				automaticBackupRetentionDaysCopy := int64(*elem.LustreConfiguration.AutomaticBackupRetentionDays)
				f8.AutomaticBackupRetentionDays = &automaticBackupRetentionDaysCopy
			}
			if elem.LustreConfiguration.CopyTagsToBackups != nil {
				f8.CopyTagsToBackups = elem.LustreConfiguration.CopyTagsToBackups
			}
			if elem.LustreConfiguration.DailyAutomaticBackupStartTime != nil {
				f8.DailyAutomaticBackupStartTime = elem.LustreConfiguration.DailyAutomaticBackupStartTime
			}
			if elem.LustreConfiguration.DataCompressionType != "" {
				f8.DataCompressionType = aws.String(string(elem.LustreConfiguration.DataCompressionType))
			}
			if elem.LustreConfiguration.DataReadCacheConfiguration != nil {
				f8f4 := &svcapitypes.LustreReadCacheConfiguration{}
				if elem.LustreConfiguration.DataReadCacheConfiguration.SizeGiB != nil {
					sizeGiBCopy := int64(*elem.LustreConfiguration.DataReadCacheConfiguration.SizeGiB)
					f8f4.SizeGiB = &sizeGiBCopy
				}
				if elem.LustreConfiguration.DataReadCacheConfiguration.SizingMode != "" {
					f8f4.SizingMode = aws.String(string(elem.LustreConfiguration.DataReadCacheConfiguration.SizingMode))
				}
				f8.DataReadCacheConfiguration = f8f4
			}
			if elem.LustreConfiguration.DeploymentType != "" {
				f8.DeploymentType = aws.String(string(elem.LustreConfiguration.DeploymentType))
			}
			if elem.LustreConfiguration.DriveCacheType != "" {
				f8.DriveCacheType = aws.String(string(elem.LustreConfiguration.DriveCacheType))
			}
			if elem.LustreConfiguration.EfaEnabled != nil {
				f8.EfaEnabled = elem.LustreConfiguration.EfaEnabled
			}
			if elem.LustreConfiguration.LogConfiguration != nil {
				f8f9 := &svcapitypes.LustreLogCreateConfiguration{}
				if elem.LustreConfiguration.LogConfiguration.Destination != nil {
					f8f9.Destination = elem.LustreConfiguration.LogConfiguration.Destination
				}
				if elem.LustreConfiguration.LogConfiguration.Level != "" {
					f8f9.Level = aws.String(string(elem.LustreConfiguration.LogConfiguration.Level))
				}
				f8.LogConfiguration = f8f9
			}
			if elem.LustreConfiguration.MetadataConfiguration != nil {
				f8f10 := &svcapitypes.CreateFileSystemLustreMetadataConfiguration{}
				if elem.LustreConfiguration.MetadataConfiguration.Iops != nil {
					iopsCopy := int64(*elem.LustreConfiguration.MetadataConfiguration.Iops)
					f8f10.IOPS = &iopsCopy
				}
				if elem.LustreConfiguration.MetadataConfiguration.Mode != "" {
					f8f10.Mode = aws.String(string(elem.LustreConfiguration.MetadataConfiguration.Mode))
				}
				f8.MetadataConfiguration = f8f10
			}
			if elem.LustreConfiguration.PerUnitStorageThroughput != nil {
				perUnitStorageThroughputCopy := int64(*elem.LustreConfiguration.PerUnitStorageThroughput)
				f8.PerUnitStorageThroughput = &perUnitStorageThroughputCopy
			}
			if elem.LustreConfiguration.RootSquashConfiguration != nil {
				f8f13 := &svcapitypes.LustreRootSquashConfiguration{}
				if elem.LustreConfiguration.RootSquashConfiguration.NoSquashNids != nil {
					f8f13.NoSquashNids = aws.StringSlice(elem.LustreConfiguration.RootSquashConfiguration.NoSquashNids)
				}
				if elem.LustreConfiguration.RootSquashConfiguration.RootSquash != nil {
					f8f13.RootSquash = elem.LustreConfiguration.RootSquashConfiguration.RootSquash
				}
				f8.RootSquashConfiguration = f8f13
			}
			if elem.LustreConfiguration.ThroughputCapacity != nil {
				throughputCapacityCopy := int64(*elem.LustreConfiguration.ThroughputCapacity)
				f8.ThroughputCapacity = &throughputCapacityCopy
			}
			if elem.LustreConfiguration.WeeklyMaintenanceStartTime != nil {
				f8.WeeklyMaintenanceStartTime = elem.LustreConfiguration.WeeklyMaintenanceStartTime
			}
			ko.Spec.LustreConfiguration = f8
		} else {
			ko.Spec.LustreConfiguration = nil
		}
		if elem.NetworkInterfaceIds != nil {
			ko.Status.NetworkInterfaceIDs = aws.StringSlice(elem.NetworkInterfaceIds)
		} else {
			ko.Status.NetworkInterfaceIDs = nil
		}
		if elem.NetworkType != "" {
			ko.Spec.NetworkType = aws.String(string(elem.NetworkType))
		} else {
			ko.Spec.NetworkType = nil
		}
		if elem.OntapConfiguration != nil {
			f11 := &svcapitypes.CreateFileSystemOntapConfiguration{}
			if elem.OntapConfiguration.AutomaticBackupRetentionDays != nil {
				automaticBackupRetentionDaysCopy := int64(*elem.OntapConfiguration.AutomaticBackupRetentionDays)
				f11.AutomaticBackupRetentionDays = &automaticBackupRetentionDaysCopy
			}
			if elem.OntapConfiguration.DailyAutomaticBackupStartTime != nil {
				f11.DailyAutomaticBackupStartTime = elem.OntapConfiguration.DailyAutomaticBackupStartTime
			}
			if elem.OntapConfiguration.DeploymentType != "" {
				f11.DeploymentType = aws.String(string(elem.OntapConfiguration.DeploymentType))
			}
			if elem.OntapConfiguration.DiskIopsConfiguration != nil {
				f11f3 := &svcapitypes.DiskIOPSConfiguration{}
				if elem.OntapConfiguration.DiskIopsConfiguration.Iops != nil {
					f11f3.IOPS = elem.OntapConfiguration.DiskIopsConfiguration.Iops
				}
				if elem.OntapConfiguration.DiskIopsConfiguration.Mode != "" {
					f11f3.Mode = aws.String(string(elem.OntapConfiguration.DiskIopsConfiguration.Mode))
				}
				f11.DiskIOPSConfiguration = f11f3
			}
			if elem.OntapConfiguration.EndpointIpAddressRange != nil {
				f11.EndpointIPAddressRange = elem.OntapConfiguration.EndpointIpAddressRange
			}
			if elem.OntapConfiguration.EndpointIpv6AddressRange != nil {
				f11.EndpointIPv6AddressRange = elem.OntapConfiguration.EndpointIpv6AddressRange
			}
			if elem.OntapConfiguration.HAPairs != nil {
				hAPairsCopy := int64(*elem.OntapConfiguration.HAPairs)
				f11.HAPairs = &hAPairsCopy
			}
			if elem.OntapConfiguration.PreferredSubnetId != nil {
				f11.PreferredSubnetID = elem.OntapConfiguration.PreferredSubnetId
			}
			if elem.OntapConfiguration.RouteTableIds != nil {
				f11.RouteTableIDs = aws.StringSlice(elem.OntapConfiguration.RouteTableIds)
			}
			if elem.OntapConfiguration.ThroughputCapacity != nil {
				throughputCapacityCopy := int64(*elem.OntapConfiguration.ThroughputCapacity)
				f11.ThroughputCapacity = &throughputCapacityCopy
			}
			if elem.OntapConfiguration.ThroughputCapacityPerHAPair != nil {
				throughputCapacityPerHAPairCopy := int64(*elem.OntapConfiguration.ThroughputCapacityPerHAPair)
				f11.ThroughputCapacityPerHAPair = &throughputCapacityPerHAPairCopy
			}
			if elem.OntapConfiguration.WeeklyMaintenanceStartTime != nil {
				f11.WeeklyMaintenanceStartTime = elem.OntapConfiguration.WeeklyMaintenanceStartTime
			}
			ko.Spec.OntapConfiguration = f11
		} else {
			ko.Spec.OntapConfiguration = nil
		}
		if elem.OpenZFSConfiguration != nil {
			f12 := &svcapitypes.CreateFileSystemOpenZFSConfiguration{}
			if elem.OpenZFSConfiguration.AutomaticBackupRetentionDays != nil {
				automaticBackupRetentionDaysCopy := int64(*elem.OpenZFSConfiguration.AutomaticBackupRetentionDays)
				f12.AutomaticBackupRetentionDays = &automaticBackupRetentionDaysCopy
			}
			if elem.OpenZFSConfiguration.CopyTagsToBackups != nil {
				f12.CopyTagsToBackups = elem.OpenZFSConfiguration.CopyTagsToBackups
			}
			if elem.OpenZFSConfiguration.CopyTagsToVolumes != nil {
				f12.CopyTagsToVolumes = elem.OpenZFSConfiguration.CopyTagsToVolumes
			}
			if elem.OpenZFSConfiguration.DailyAutomaticBackupStartTime != nil {
				f12.DailyAutomaticBackupStartTime = elem.OpenZFSConfiguration.DailyAutomaticBackupStartTime
			}
			if elem.OpenZFSConfiguration.DeploymentType != "" {
				f12.DeploymentType = aws.String(string(elem.OpenZFSConfiguration.DeploymentType))
			}
			if elem.OpenZFSConfiguration.DiskIopsConfiguration != nil {
				f12f5 := &svcapitypes.DiskIOPSConfiguration{}
				if elem.OpenZFSConfiguration.DiskIopsConfiguration.Iops != nil {
					f12f5.IOPS = elem.OpenZFSConfiguration.DiskIopsConfiguration.Iops
				}
				if elem.OpenZFSConfiguration.DiskIopsConfiguration.Mode != "" {
					f12f5.Mode = aws.String(string(elem.OpenZFSConfiguration.DiskIopsConfiguration.Mode))
				}
				f12.DiskIOPSConfiguration = f12f5
			}
			if elem.OpenZFSConfiguration.EndpointIpAddressRange != nil {
				f12.EndpointIPAddressRange = elem.OpenZFSConfiguration.EndpointIpAddressRange
			}
			if elem.OpenZFSConfiguration.EndpointIpv6AddressRange != nil {
				f12.EndpointIPv6AddressRange = elem.OpenZFSConfiguration.EndpointIpv6AddressRange
			}
			if elem.OpenZFSConfiguration.PreferredSubnetId != nil {
				f12.PreferredSubnetID = elem.OpenZFSConfiguration.PreferredSubnetId
			}
			if elem.OpenZFSConfiguration.ReadCacheConfiguration != nil {
				f12f11 := &svcapitypes.OpenZFSReadCacheConfiguration{}
				if elem.OpenZFSConfiguration.ReadCacheConfiguration.SizeGiB != nil {
					sizeGiBCopy := int64(*elem.OpenZFSConfiguration.ReadCacheConfiguration.SizeGiB)
					f12f11.SizeGiB = &sizeGiBCopy
				}
				if elem.OpenZFSConfiguration.ReadCacheConfiguration.SizingMode != "" {
					f12f11.SizingMode = aws.String(string(elem.OpenZFSConfiguration.ReadCacheConfiguration.SizingMode))
				}
				f12.ReadCacheConfiguration = f12f11
			}
			if elem.OpenZFSConfiguration.RouteTableIds != nil {
				f12.RouteTableIDs = aws.StringSlice(elem.OpenZFSConfiguration.RouteTableIds)
			}
			if elem.OpenZFSConfiguration.ThroughputCapacity != nil {
				throughputCapacityCopy := int64(*elem.OpenZFSConfiguration.ThroughputCapacity)
				f12.ThroughputCapacity = &throughputCapacityCopy
			}
			if elem.OpenZFSConfiguration.WeeklyMaintenanceStartTime != nil {
				f12.WeeklyMaintenanceStartTime = elem.OpenZFSConfiguration.WeeklyMaintenanceStartTime
			}
			ko.Spec.OpenZFSConfiguration = f12
		} else {
			ko.Spec.OpenZFSConfiguration = nil
		}
		if elem.OwnerId != nil {
			ko.Status.OwnerID = elem.OwnerId
		} else {
			ko.Status.OwnerID = nil
		}
		if elem.ResourceARN != nil {
			if ko.Status.ACKResourceMetadata == nil {
				ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
			}
			tmpARN := ackv1alpha1.AWSResourceName(*elem.ResourceARN)
			ko.Status.ACKResourceMetadata.ARN = &tmpARN
		}
		if elem.StorageCapacity != nil {
			storageCapacityCopy := int64(*elem.StorageCapacity)
			ko.Spec.StorageCapacity = &storageCapacityCopy
		} else {
			ko.Spec.StorageCapacity = nil
		}
		if elem.StorageType != "" {
			ko.Spec.StorageType = aws.String(string(elem.StorageType))
		} else {
			ko.Spec.StorageType = nil
		}
		if elem.SubnetIds != nil {
			ko.Spec.SubnetIDs = aws.StringSlice(elem.SubnetIds)
		} else {
			ko.Spec.SubnetIDs = nil
		}
		if elem.Tags != nil {
			f18 := []*svcapitypes.Tag{}
			for _, f18iter := range elem.Tags {
				f18elem := &svcapitypes.Tag{}
				if f18iter.Key != nil {
					f18elem.Key = f18iter.Key
				}
				if f18iter.Value != nil {
					f18elem.Value = f18iter.Value
				}
				f18 = append(f18, f18elem)
			}
			ko.Spec.Tags = f18
		} else {
			ko.Spec.Tags = nil
		}
		if elem.VpcId != nil {
			ko.Status.VPCID = elem.VpcId
		} else {
			ko.Status.VPCID = nil
		}
		if elem.WindowsConfiguration != nil {
			f20 := &svcapitypes.CreateFileSystemWindowsConfiguration{}
			if elem.WindowsConfiguration.ActiveDirectoryId != nil {
				f20.ActiveDirectoryID = elem.WindowsConfiguration.ActiveDirectoryId
			}
			if elem.WindowsConfiguration.AuditLogConfiguration != nil {
				f20f1 := &svcapitypes.WindowsAuditLogCreateConfiguration{}
				if elem.WindowsConfiguration.AuditLogConfiguration.AuditLogDestination != nil {
					f20f1.AuditLogDestination = elem.WindowsConfiguration.AuditLogConfiguration.AuditLogDestination
				}
				if elem.WindowsConfiguration.AuditLogConfiguration.FileAccessAuditLogLevel != "" {
					f20f1.FileAccessAuditLogLevel = aws.String(string(elem.WindowsConfiguration.AuditLogConfiguration.FileAccessAuditLogLevel))
				}
				if elem.WindowsConfiguration.AuditLogConfiguration.FileShareAccessAuditLogLevel != "" {
					f20f1.FileShareAccessAuditLogLevel = aws.String(string(elem.WindowsConfiguration.AuditLogConfiguration.FileShareAccessAuditLogLevel))
				}
				f20.AuditLogConfiguration = f20f1
			}
			if elem.WindowsConfiguration.AutomaticBackupRetentionDays != nil {
				automaticBackupRetentionDaysCopy := int64(*elem.WindowsConfiguration.AutomaticBackupRetentionDays)
				f20.AutomaticBackupRetentionDays = &automaticBackupRetentionDaysCopy
			}
			if elem.WindowsConfiguration.CopyTagsToBackups != nil {
				f20.CopyTagsToBackups = elem.WindowsConfiguration.CopyTagsToBackups
			}
			if elem.WindowsConfiguration.DailyAutomaticBackupStartTime != nil {
				f20.DailyAutomaticBackupStartTime = elem.WindowsConfiguration.DailyAutomaticBackupStartTime
			}
			if elem.WindowsConfiguration.DeploymentType != "" {
				f20.DeploymentType = aws.String(string(elem.WindowsConfiguration.DeploymentType))
			}
			if elem.WindowsConfiguration.DiskIopsConfiguration != nil {
				f20f6 := &svcapitypes.DiskIOPSConfiguration{}
				if elem.WindowsConfiguration.DiskIopsConfiguration.Iops != nil {
					f20f6.IOPS = elem.WindowsConfiguration.DiskIopsConfiguration.Iops
				}
				if elem.WindowsConfiguration.DiskIopsConfiguration.Mode != "" {
					f20f6.Mode = aws.String(string(elem.WindowsConfiguration.DiskIopsConfiguration.Mode))
				}
				f20.DiskIOPSConfiguration = f20f6
			}
			if elem.WindowsConfiguration.FsrmConfiguration != nil {
				f20f7 := &svcapitypes.WindowsFsrmConfiguration{}
				if elem.WindowsConfiguration.FsrmConfiguration.EventLogDestination != nil {
					f20f7.EventLogDestination = elem.WindowsConfiguration.FsrmConfiguration.EventLogDestination
				}
				if elem.WindowsConfiguration.FsrmConfiguration.FsrmServiceEnabled != nil {
					f20f7.FsrmServiceEnabled = elem.WindowsConfiguration.FsrmConfiguration.FsrmServiceEnabled
				}
				f20.FsrmConfiguration = f20f7
			}
			if elem.WindowsConfiguration.PreferredSubnetId != nil {
				f20.PreferredSubnetID = elem.WindowsConfiguration.PreferredSubnetId
			}
			if elem.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration != nil {
				f20f13 := &svcapitypes.SelfManagedActiveDirectoryConfiguration{}
				if elem.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.DnsIps != nil {
					f20f13.DNSIPs = aws.StringSlice(elem.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.DnsIps)
				}
				if elem.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.DomainJoinServiceAccountSecret != nil {
					f20f13.DomainJoinServiceAccountSecret = elem.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.DomainJoinServiceAccountSecret
				}
				if elem.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.DomainName != nil {
					f20f13.DomainName = elem.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.DomainName
				}
				if elem.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.FileSystemAdministratorsGroup != nil {
					f20f13.FileSystemAdministratorsGroup = elem.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.FileSystemAdministratorsGroup
				}
				if elem.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.OrganizationalUnitDistinguishedName != nil {
					f20f13.OrganizationalUnitDistinguishedName = elem.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.OrganizationalUnitDistinguishedName
				}
				if elem.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.UserName != nil {
					f20f13.UserName = elem.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.UserName
				}
				f20.SelfManagedActiveDirectoryConfiguration = f20f13
			}
			if elem.WindowsConfiguration.ThroughputCapacity != nil {
				throughputCapacityCopy := int64(*elem.WindowsConfiguration.ThroughputCapacity)
				f20.ThroughputCapacity = &throughputCapacityCopy
			}
			if elem.WindowsConfiguration.WeeklyMaintenanceStartTime != nil {
				f20.WeeklyMaintenanceStartTime = elem.WindowsConfiguration.WeeklyMaintenanceStartTime
			}
			ko.Spec.WindowsConfiguration = f20
		} else {
			ko.Spec.WindowsConfiguration = nil
		}
		found = true
		break
	}
	if !found {
		return nil, ackerr.NotFound
	}

	rm.setStatusDefaults(ko)
	restoreNonRoundTrippedSpecFields(r, ko)
	recoverObservedLustreDataRepository(r, resp, ko)
	ensureLastAppliedSecretBaseline(ko)
	ensureImmutableFieldBaseline(ko)
	if err := terminalIfFailed(ko); err != nil {
		return &resource{ko}, err
	}

	return &resource{ko}, nil
}

// requiredFieldsMissingFromReadManyInput returns true if there are any fields
// for the ReadMany Input shape that are required but not present in the
// resource's Spec or Status
func (rm *resourceManager) requiredFieldsMissingFromReadManyInput(
	r *resource,
) bool {
	return r.ko.Status.FileSystemID == nil

}

// newListRequestPayload returns SDK-specific struct for the HTTP request
// payload of the List API call for the resource
func (rm *resourceManager) newListRequestPayload(
	r *resource,
) (*svcsdk.DescribeFileSystemsInput, error) {
	res := &svcsdk.DescribeFileSystemsInput{}

	if r.ko.Status.FileSystemID != nil {
		f0 := []string{}
		f0 = append(f0, *r.ko.Status.FileSystemID)
		res.FileSystemIds = f0
	}

	return res, nil
}

// sdkCreate creates the supplied resource in the backend AWS service API and
// returns a copy of the resource with resource fields (in both Spec and
// Status) filled in with values from the CREATE API operation's Output shape.
func (rm *resourceManager) sdkCreate(
	ctx context.Context,
	desired *resource,
) (created *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkCreate")
	defer func() {
		exit(err)
	}()
	input, err := rm.newCreateRequestPayload(ctx, desired)
	if err != nil {
		return nil, err
	}
	// The generated builder omits a password whose referenced Secret resolves to
	// an empty value. Creation could then succeed without it while the reference
	// is recorded as applied, after which filling that Secret would never be
	// detected -- comparison tracks the reference, not the value.
	if err := rejectEmptyResolvedPasswords(desired, input); err != nil {
		return nil, err
	}

	var resp *svcsdk.CreateFileSystemOutput
	_ = resp
	resp, err = rm.sdkapi.CreateFileSystem(ctx, input)
	rm.metrics.RecordAPICall("CREATE", "CreateFileSystem", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if resp.FileSystem.CreationTime != nil {
		ko.Status.CreationTime = &metav1.Time{*resp.FileSystem.CreationTime}
	} else {
		ko.Status.CreationTime = nil
	}
	if resp.FileSystem.DNSName != nil {
		ko.Status.DNSName = resp.FileSystem.DNSName
	} else {
		ko.Status.DNSName = nil
	}
	if resp.FileSystem.FailureDetails != nil {
		f2 := &svcapitypes.FileSystemFailureDetails{}
		if resp.FileSystem.FailureDetails.Message != nil {
			f2.Message = resp.FileSystem.FailureDetails.Message
		}
		ko.Status.FailureDetails = f2
	} else {
		ko.Status.FailureDetails = nil
	}
	if resp.FileSystem.FileSystemId != nil {
		ko.Status.FileSystemID = resp.FileSystem.FileSystemId
	} else {
		ko.Status.FileSystemID = nil
	}
	if resp.FileSystem.FileSystemType != "" {
		ko.Spec.FileSystemType = aws.String(string(resp.FileSystem.FileSystemType))
	} else {
		ko.Spec.FileSystemType = nil
	}
	if resp.FileSystem.FileSystemTypeVersion != nil {
		ko.Spec.FileSystemTypeVersion = resp.FileSystem.FileSystemTypeVersion
	} else {
		ko.Spec.FileSystemTypeVersion = nil
	}
	if resp.FileSystem.KmsKeyId != nil {
		ko.Spec.KMSKeyID = resp.FileSystem.KmsKeyId
	} else {
		ko.Spec.KMSKeyID = nil
	}
	if resp.FileSystem.Lifecycle != "" {
		ko.Status.Lifecycle = aws.String(string(resp.FileSystem.Lifecycle))
	} else {
		ko.Status.Lifecycle = nil
	}
	if resp.FileSystem.LustreConfiguration != nil {
		f8 := &svcapitypes.CreateFileSystemLustreConfiguration{}
		if resp.FileSystem.LustreConfiguration.AutomaticBackupRetentionDays != nil {
			automaticBackupRetentionDaysCopy := int64(*resp.FileSystem.LustreConfiguration.AutomaticBackupRetentionDays)
			f8.AutomaticBackupRetentionDays = &automaticBackupRetentionDaysCopy
		}
		if resp.FileSystem.LustreConfiguration.CopyTagsToBackups != nil {
			f8.CopyTagsToBackups = resp.FileSystem.LustreConfiguration.CopyTagsToBackups
		}
		if resp.FileSystem.LustreConfiguration.DailyAutomaticBackupStartTime != nil {
			f8.DailyAutomaticBackupStartTime = resp.FileSystem.LustreConfiguration.DailyAutomaticBackupStartTime
		}
		if resp.FileSystem.LustreConfiguration.DataCompressionType != "" {
			f8.DataCompressionType = aws.String(string(resp.FileSystem.LustreConfiguration.DataCompressionType))
		}
		if resp.FileSystem.LustreConfiguration.DataReadCacheConfiguration != nil {
			f8f4 := &svcapitypes.LustreReadCacheConfiguration{}
			if resp.FileSystem.LustreConfiguration.DataReadCacheConfiguration.SizeGiB != nil {
				sizeGiBCopy := int64(*resp.FileSystem.LustreConfiguration.DataReadCacheConfiguration.SizeGiB)
				f8f4.SizeGiB = &sizeGiBCopy
			}
			if resp.FileSystem.LustreConfiguration.DataReadCacheConfiguration.SizingMode != "" {
				f8f4.SizingMode = aws.String(string(resp.FileSystem.LustreConfiguration.DataReadCacheConfiguration.SizingMode))
			}
			f8.DataReadCacheConfiguration = f8f4
		}
		if resp.FileSystem.LustreConfiguration.DeploymentType != "" {
			f8.DeploymentType = aws.String(string(resp.FileSystem.LustreConfiguration.DeploymentType))
		}
		if resp.FileSystem.LustreConfiguration.DriveCacheType != "" {
			f8.DriveCacheType = aws.String(string(resp.FileSystem.LustreConfiguration.DriveCacheType))
		}
		if resp.FileSystem.LustreConfiguration.EfaEnabled != nil {
			f8.EfaEnabled = resp.FileSystem.LustreConfiguration.EfaEnabled
		}
		if resp.FileSystem.LustreConfiguration.LogConfiguration != nil {
			f8f9 := &svcapitypes.LustreLogCreateConfiguration{}
			if resp.FileSystem.LustreConfiguration.LogConfiguration.Destination != nil {
				f8f9.Destination = resp.FileSystem.LustreConfiguration.LogConfiguration.Destination
			}
			if resp.FileSystem.LustreConfiguration.LogConfiguration.Level != "" {
				f8f9.Level = aws.String(string(resp.FileSystem.LustreConfiguration.LogConfiguration.Level))
			}
			f8.LogConfiguration = f8f9
		}
		if resp.FileSystem.LustreConfiguration.MetadataConfiguration != nil {
			f8f10 := &svcapitypes.CreateFileSystemLustreMetadataConfiguration{}
			if resp.FileSystem.LustreConfiguration.MetadataConfiguration.Iops != nil {
				iopsCopy := int64(*resp.FileSystem.LustreConfiguration.MetadataConfiguration.Iops)
				f8f10.IOPS = &iopsCopy
			}
			if resp.FileSystem.LustreConfiguration.MetadataConfiguration.Mode != "" {
				f8f10.Mode = aws.String(string(resp.FileSystem.LustreConfiguration.MetadataConfiguration.Mode))
			}
			f8.MetadataConfiguration = f8f10
		}
		if resp.FileSystem.LustreConfiguration.PerUnitStorageThroughput != nil {
			perUnitStorageThroughputCopy := int64(*resp.FileSystem.LustreConfiguration.PerUnitStorageThroughput)
			f8.PerUnitStorageThroughput = &perUnitStorageThroughputCopy
		}
		if resp.FileSystem.LustreConfiguration.RootSquashConfiguration != nil {
			f8f13 := &svcapitypes.LustreRootSquashConfiguration{}
			if resp.FileSystem.LustreConfiguration.RootSquashConfiguration.NoSquashNids != nil {
				f8f13.NoSquashNids = aws.StringSlice(resp.FileSystem.LustreConfiguration.RootSquashConfiguration.NoSquashNids)
			}
			if resp.FileSystem.LustreConfiguration.RootSquashConfiguration.RootSquash != nil {
				f8f13.RootSquash = resp.FileSystem.LustreConfiguration.RootSquashConfiguration.RootSquash
			}
			f8.RootSquashConfiguration = f8f13
		}
		if resp.FileSystem.LustreConfiguration.ThroughputCapacity != nil {
			throughputCapacityCopy := int64(*resp.FileSystem.LustreConfiguration.ThroughputCapacity)
			f8.ThroughputCapacity = &throughputCapacityCopy
		}
		if resp.FileSystem.LustreConfiguration.WeeklyMaintenanceStartTime != nil {
			f8.WeeklyMaintenanceStartTime = resp.FileSystem.LustreConfiguration.WeeklyMaintenanceStartTime
		}
		ko.Spec.LustreConfiguration = f8
	} else {
		ko.Spec.LustreConfiguration = nil
	}
	if resp.FileSystem.NetworkInterfaceIds != nil {
		ko.Status.NetworkInterfaceIDs = aws.StringSlice(resp.FileSystem.NetworkInterfaceIds)
	} else {
		ko.Status.NetworkInterfaceIDs = nil
	}
	if resp.FileSystem.NetworkType != "" {
		ko.Spec.NetworkType = aws.String(string(resp.FileSystem.NetworkType))
	} else {
		ko.Spec.NetworkType = nil
	}
	if resp.FileSystem.OntapConfiguration != nil {
		f11 := &svcapitypes.CreateFileSystemOntapConfiguration{}
		if resp.FileSystem.OntapConfiguration.AutomaticBackupRetentionDays != nil {
			automaticBackupRetentionDaysCopy := int64(*resp.FileSystem.OntapConfiguration.AutomaticBackupRetentionDays)
			f11.AutomaticBackupRetentionDays = &automaticBackupRetentionDaysCopy
		}
		if resp.FileSystem.OntapConfiguration.DailyAutomaticBackupStartTime != nil {
			f11.DailyAutomaticBackupStartTime = resp.FileSystem.OntapConfiguration.DailyAutomaticBackupStartTime
		}
		if resp.FileSystem.OntapConfiguration.DeploymentType != "" {
			f11.DeploymentType = aws.String(string(resp.FileSystem.OntapConfiguration.DeploymentType))
		}
		if resp.FileSystem.OntapConfiguration.DiskIopsConfiguration != nil {
			f11f3 := &svcapitypes.DiskIOPSConfiguration{}
			if resp.FileSystem.OntapConfiguration.DiskIopsConfiguration.Iops != nil {
				f11f3.IOPS = resp.FileSystem.OntapConfiguration.DiskIopsConfiguration.Iops
			}
			if resp.FileSystem.OntapConfiguration.DiskIopsConfiguration.Mode != "" {
				f11f3.Mode = aws.String(string(resp.FileSystem.OntapConfiguration.DiskIopsConfiguration.Mode))
			}
			f11.DiskIOPSConfiguration = f11f3
		}
		if resp.FileSystem.OntapConfiguration.EndpointIpAddressRange != nil {
			f11.EndpointIPAddressRange = resp.FileSystem.OntapConfiguration.EndpointIpAddressRange
		}
		if resp.FileSystem.OntapConfiguration.EndpointIpv6AddressRange != nil {
			f11.EndpointIPv6AddressRange = resp.FileSystem.OntapConfiguration.EndpointIpv6AddressRange
		}
		if resp.FileSystem.OntapConfiguration.HAPairs != nil {
			hAPairsCopy := int64(*resp.FileSystem.OntapConfiguration.HAPairs)
			f11.HAPairs = &hAPairsCopy
		}
		if resp.FileSystem.OntapConfiguration.PreferredSubnetId != nil {
			f11.PreferredSubnetID = resp.FileSystem.OntapConfiguration.PreferredSubnetId
		}
		if resp.FileSystem.OntapConfiguration.RouteTableIds != nil {
			f11.RouteTableIDs = aws.StringSlice(resp.FileSystem.OntapConfiguration.RouteTableIds)
		}
		if resp.FileSystem.OntapConfiguration.ThroughputCapacity != nil {
			throughputCapacityCopy := int64(*resp.FileSystem.OntapConfiguration.ThroughputCapacity)
			f11.ThroughputCapacity = &throughputCapacityCopy
		}
		if resp.FileSystem.OntapConfiguration.ThroughputCapacityPerHAPair != nil {
			throughputCapacityPerHAPairCopy := int64(*resp.FileSystem.OntapConfiguration.ThroughputCapacityPerHAPair)
			f11.ThroughputCapacityPerHAPair = &throughputCapacityPerHAPairCopy
		}
		if resp.FileSystem.OntapConfiguration.WeeklyMaintenanceStartTime != nil {
			f11.WeeklyMaintenanceStartTime = resp.FileSystem.OntapConfiguration.WeeklyMaintenanceStartTime
		}
		ko.Spec.OntapConfiguration = f11
	} else {
		ko.Spec.OntapConfiguration = nil
	}
	if resp.FileSystem.OpenZFSConfiguration != nil {
		f12 := &svcapitypes.CreateFileSystemOpenZFSConfiguration{}
		if resp.FileSystem.OpenZFSConfiguration.AutomaticBackupRetentionDays != nil {
			automaticBackupRetentionDaysCopy := int64(*resp.FileSystem.OpenZFSConfiguration.AutomaticBackupRetentionDays)
			f12.AutomaticBackupRetentionDays = &automaticBackupRetentionDaysCopy
		}
		if resp.FileSystem.OpenZFSConfiguration.CopyTagsToBackups != nil {
			f12.CopyTagsToBackups = resp.FileSystem.OpenZFSConfiguration.CopyTagsToBackups
		}
		if resp.FileSystem.OpenZFSConfiguration.CopyTagsToVolumes != nil {
			f12.CopyTagsToVolumes = resp.FileSystem.OpenZFSConfiguration.CopyTagsToVolumes
		}
		if resp.FileSystem.OpenZFSConfiguration.DailyAutomaticBackupStartTime != nil {
			f12.DailyAutomaticBackupStartTime = resp.FileSystem.OpenZFSConfiguration.DailyAutomaticBackupStartTime
		}
		if resp.FileSystem.OpenZFSConfiguration.DeploymentType != "" {
			f12.DeploymentType = aws.String(string(resp.FileSystem.OpenZFSConfiguration.DeploymentType))
		}
		if resp.FileSystem.OpenZFSConfiguration.DiskIopsConfiguration != nil {
			f12f5 := &svcapitypes.DiskIOPSConfiguration{}
			if resp.FileSystem.OpenZFSConfiguration.DiskIopsConfiguration.Iops != nil {
				f12f5.IOPS = resp.FileSystem.OpenZFSConfiguration.DiskIopsConfiguration.Iops
			}
			if resp.FileSystem.OpenZFSConfiguration.DiskIopsConfiguration.Mode != "" {
				f12f5.Mode = aws.String(string(resp.FileSystem.OpenZFSConfiguration.DiskIopsConfiguration.Mode))
			}
			f12.DiskIOPSConfiguration = f12f5
		}
		if resp.FileSystem.OpenZFSConfiguration.EndpointIpAddressRange != nil {
			f12.EndpointIPAddressRange = resp.FileSystem.OpenZFSConfiguration.EndpointIpAddressRange
		}
		if resp.FileSystem.OpenZFSConfiguration.EndpointIpv6AddressRange != nil {
			f12.EndpointIPv6AddressRange = resp.FileSystem.OpenZFSConfiguration.EndpointIpv6AddressRange
		}
		if resp.FileSystem.OpenZFSConfiguration.PreferredSubnetId != nil {
			f12.PreferredSubnetID = resp.FileSystem.OpenZFSConfiguration.PreferredSubnetId
		}
		if resp.FileSystem.OpenZFSConfiguration.ReadCacheConfiguration != nil {
			f12f11 := &svcapitypes.OpenZFSReadCacheConfiguration{}
			if resp.FileSystem.OpenZFSConfiguration.ReadCacheConfiguration.SizeGiB != nil {
				sizeGiBCopy := int64(*resp.FileSystem.OpenZFSConfiguration.ReadCacheConfiguration.SizeGiB)
				f12f11.SizeGiB = &sizeGiBCopy
			}
			if resp.FileSystem.OpenZFSConfiguration.ReadCacheConfiguration.SizingMode != "" {
				f12f11.SizingMode = aws.String(string(resp.FileSystem.OpenZFSConfiguration.ReadCacheConfiguration.SizingMode))
			}
			f12.ReadCacheConfiguration = f12f11
		}
		if resp.FileSystem.OpenZFSConfiguration.RouteTableIds != nil {
			f12.RouteTableIDs = aws.StringSlice(resp.FileSystem.OpenZFSConfiguration.RouteTableIds)
		}
		if resp.FileSystem.OpenZFSConfiguration.ThroughputCapacity != nil {
			throughputCapacityCopy := int64(*resp.FileSystem.OpenZFSConfiguration.ThroughputCapacity)
			f12.ThroughputCapacity = &throughputCapacityCopy
		}
		if resp.FileSystem.OpenZFSConfiguration.WeeklyMaintenanceStartTime != nil {
			f12.WeeklyMaintenanceStartTime = resp.FileSystem.OpenZFSConfiguration.WeeklyMaintenanceStartTime
		}
		ko.Spec.OpenZFSConfiguration = f12
	} else {
		ko.Spec.OpenZFSConfiguration = nil
	}
	if resp.FileSystem.OwnerId != nil {
		ko.Status.OwnerID = resp.FileSystem.OwnerId
	} else {
		ko.Status.OwnerID = nil
	}
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.FileSystem.ResourceARN != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.FileSystem.ResourceARN)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}
	if resp.FileSystem.StorageCapacity != nil {
		storageCapacityCopy := int64(*resp.FileSystem.StorageCapacity)
		ko.Spec.StorageCapacity = &storageCapacityCopy
	} else {
		ko.Spec.StorageCapacity = nil
	}
	if resp.FileSystem.StorageType != "" {
		ko.Spec.StorageType = aws.String(string(resp.FileSystem.StorageType))
	} else {
		ko.Spec.StorageType = nil
	}
	if resp.FileSystem.SubnetIds != nil {
		ko.Spec.SubnetIDs = aws.StringSlice(resp.FileSystem.SubnetIds)
	} else {
		ko.Spec.SubnetIDs = nil
	}
	if resp.FileSystem.Tags != nil {
		f18 := []*svcapitypes.Tag{}
		for _, f18iter := range resp.FileSystem.Tags {
			f18elem := &svcapitypes.Tag{}
			if f18iter.Key != nil {
				f18elem.Key = f18iter.Key
			}
			if f18iter.Value != nil {
				f18elem.Value = f18iter.Value
			}
			f18 = append(f18, f18elem)
		}
		ko.Spec.Tags = f18
	} else {
		ko.Spec.Tags = nil
	}
	if resp.FileSystem.VpcId != nil {
		ko.Status.VPCID = resp.FileSystem.VpcId
	} else {
		ko.Status.VPCID = nil
	}
	if resp.FileSystem.WindowsConfiguration != nil {
		f20 := &svcapitypes.CreateFileSystemWindowsConfiguration{}
		if resp.FileSystem.WindowsConfiguration.ActiveDirectoryId != nil {
			f20.ActiveDirectoryID = resp.FileSystem.WindowsConfiguration.ActiveDirectoryId
		}
		if resp.FileSystem.WindowsConfiguration.AuditLogConfiguration != nil {
			f20f1 := &svcapitypes.WindowsAuditLogCreateConfiguration{}
			if resp.FileSystem.WindowsConfiguration.AuditLogConfiguration.AuditLogDestination != nil {
				f20f1.AuditLogDestination = resp.FileSystem.WindowsConfiguration.AuditLogConfiguration.AuditLogDestination
			}
			if resp.FileSystem.WindowsConfiguration.AuditLogConfiguration.FileAccessAuditLogLevel != "" {
				f20f1.FileAccessAuditLogLevel = aws.String(string(resp.FileSystem.WindowsConfiguration.AuditLogConfiguration.FileAccessAuditLogLevel))
			}
			if resp.FileSystem.WindowsConfiguration.AuditLogConfiguration.FileShareAccessAuditLogLevel != "" {
				f20f1.FileShareAccessAuditLogLevel = aws.String(string(resp.FileSystem.WindowsConfiguration.AuditLogConfiguration.FileShareAccessAuditLogLevel))
			}
			f20.AuditLogConfiguration = f20f1
		}
		if resp.FileSystem.WindowsConfiguration.AutomaticBackupRetentionDays != nil {
			automaticBackupRetentionDaysCopy := int64(*resp.FileSystem.WindowsConfiguration.AutomaticBackupRetentionDays)
			f20.AutomaticBackupRetentionDays = &automaticBackupRetentionDaysCopy
		}
		if resp.FileSystem.WindowsConfiguration.CopyTagsToBackups != nil {
			f20.CopyTagsToBackups = resp.FileSystem.WindowsConfiguration.CopyTagsToBackups
		}
		if resp.FileSystem.WindowsConfiguration.DailyAutomaticBackupStartTime != nil {
			f20.DailyAutomaticBackupStartTime = resp.FileSystem.WindowsConfiguration.DailyAutomaticBackupStartTime
		}
		if resp.FileSystem.WindowsConfiguration.DeploymentType != "" {
			f20.DeploymentType = aws.String(string(resp.FileSystem.WindowsConfiguration.DeploymentType))
		}
		if resp.FileSystem.WindowsConfiguration.DiskIopsConfiguration != nil {
			f20f6 := &svcapitypes.DiskIOPSConfiguration{}
			if resp.FileSystem.WindowsConfiguration.DiskIopsConfiguration.Iops != nil {
				f20f6.IOPS = resp.FileSystem.WindowsConfiguration.DiskIopsConfiguration.Iops
			}
			if resp.FileSystem.WindowsConfiguration.DiskIopsConfiguration.Mode != "" {
				f20f6.Mode = aws.String(string(resp.FileSystem.WindowsConfiguration.DiskIopsConfiguration.Mode))
			}
			f20.DiskIOPSConfiguration = f20f6
		}
		if resp.FileSystem.WindowsConfiguration.FsrmConfiguration != nil {
			f20f7 := &svcapitypes.WindowsFsrmConfiguration{}
			if resp.FileSystem.WindowsConfiguration.FsrmConfiguration.EventLogDestination != nil {
				f20f7.EventLogDestination = resp.FileSystem.WindowsConfiguration.FsrmConfiguration.EventLogDestination
			}
			if resp.FileSystem.WindowsConfiguration.FsrmConfiguration.FsrmServiceEnabled != nil {
				f20f7.FsrmServiceEnabled = resp.FileSystem.WindowsConfiguration.FsrmConfiguration.FsrmServiceEnabled
			}
			f20.FsrmConfiguration = f20f7
		}
		if resp.FileSystem.WindowsConfiguration.PreferredSubnetId != nil {
			f20.PreferredSubnetID = resp.FileSystem.WindowsConfiguration.PreferredSubnetId
		}
		if resp.FileSystem.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration != nil {
			f20f13 := &svcapitypes.SelfManagedActiveDirectoryConfiguration{}
			if resp.FileSystem.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.DnsIps != nil {
				f20f13.DNSIPs = aws.StringSlice(resp.FileSystem.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.DnsIps)
			}
			if resp.FileSystem.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.DomainJoinServiceAccountSecret != nil {
				f20f13.DomainJoinServiceAccountSecret = resp.FileSystem.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.DomainJoinServiceAccountSecret
			}
			if resp.FileSystem.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.DomainName != nil {
				f20f13.DomainName = resp.FileSystem.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.DomainName
			}
			if resp.FileSystem.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.FileSystemAdministratorsGroup != nil {
				f20f13.FileSystemAdministratorsGroup = resp.FileSystem.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.FileSystemAdministratorsGroup
			}
			if resp.FileSystem.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.OrganizationalUnitDistinguishedName != nil {
				f20f13.OrganizationalUnitDistinguishedName = resp.FileSystem.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.OrganizationalUnitDistinguishedName
			}
			if resp.FileSystem.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.UserName != nil {
				f20f13.UserName = resp.FileSystem.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.UserName
			}
			f20.SelfManagedActiveDirectoryConfiguration = f20f13
		}
		if resp.FileSystem.WindowsConfiguration.ThroughputCapacity != nil {
			throughputCapacityCopy := int64(*resp.FileSystem.WindowsConfiguration.ThroughputCapacity)
			f20.ThroughputCapacity = &throughputCapacityCopy
		}
		if resp.FileSystem.WindowsConfiguration.WeeklyMaintenanceStartTime != nil {
			f20.WeeklyMaintenanceStartTime = resp.FileSystem.WindowsConfiguration.WeeklyMaintenanceStartTime
		}
		ko.Spec.WindowsConfiguration = f20
	} else {
		ko.Spec.WindowsConfiguration = nil
	}

	rm.setStatusDefaults(ko)
	restoreNonRoundTrippedSpecFields(desired, ko)
	restoreLustreDataRepositoryFields(desired, ko)
	setLastAppliedSecretRefs(ko)
	setLastAppliedImmutableFields(ko)

	return &resource{ko}, nil
}

// newCreateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Create API call for the resource
func (rm *resourceManager) newCreateRequestPayload(
	ctx context.Context,
	r *resource,
) (*svcsdk.CreateFileSystemInput, error) {
	res := &svcsdk.CreateFileSystemInput{}

	if r.ko.Spec.FileSystemType != nil {
		res.FileSystemType = svcsdktypes.FileSystemType(*r.ko.Spec.FileSystemType)
	}
	if r.ko.Spec.FileSystemTypeVersion != nil {
		res.FileSystemTypeVersion = r.ko.Spec.FileSystemTypeVersion
	}
	if r.ko.Spec.KMSKeyID != nil {
		res.KmsKeyId = r.ko.Spec.KMSKeyID
	}
	if r.ko.Spec.LustreConfiguration != nil {
		f4 := &svcsdktypes.CreateFileSystemLustreConfiguration{}
		if r.ko.Spec.LustreConfiguration.AutoImportPolicy != nil {
			f4.AutoImportPolicy = svcsdktypes.AutoImportPolicyType(*r.ko.Spec.LustreConfiguration.AutoImportPolicy)
		}
		if r.ko.Spec.LustreConfiguration.AutomaticBackupRetentionDays != nil {
			automaticBackupRetentionDaysCopy0 := *r.ko.Spec.LustreConfiguration.AutomaticBackupRetentionDays
			if automaticBackupRetentionDaysCopy0 > math.MaxInt32 || automaticBackupRetentionDaysCopy0 < math.MinInt32 {
				return nil, fmt.Errorf("error: field AutomaticBackupRetentionDays is of type int32")
			}
			automaticBackupRetentionDaysCopy := int32(automaticBackupRetentionDaysCopy0)
			f4.AutomaticBackupRetentionDays = &automaticBackupRetentionDaysCopy
		}
		if r.ko.Spec.LustreConfiguration.CopyTagsToBackups != nil {
			f4.CopyTagsToBackups = r.ko.Spec.LustreConfiguration.CopyTagsToBackups
		}
		if r.ko.Spec.LustreConfiguration.DailyAutomaticBackupStartTime != nil {
			f4.DailyAutomaticBackupStartTime = r.ko.Spec.LustreConfiguration.DailyAutomaticBackupStartTime
		}
		if r.ko.Spec.LustreConfiguration.DataCompressionType != nil {
			f4.DataCompressionType = svcsdktypes.DataCompressionType(*r.ko.Spec.LustreConfiguration.DataCompressionType)
		}
		if r.ko.Spec.LustreConfiguration.DataReadCacheConfiguration != nil {
			f4f5 := &svcsdktypes.LustreReadCacheConfiguration{}
			if r.ko.Spec.LustreConfiguration.DataReadCacheConfiguration.SizeGiB != nil {
				sizeGiBCopy0 := *r.ko.Spec.LustreConfiguration.DataReadCacheConfiguration.SizeGiB
				if sizeGiBCopy0 > math.MaxInt32 || sizeGiBCopy0 < math.MinInt32 {
					return nil, fmt.Errorf("error: field SizeGiB is of type int32")
				}
				sizeGiBCopy := int32(sizeGiBCopy0)
				f4f5.SizeGiB = &sizeGiBCopy
			}
			if r.ko.Spec.LustreConfiguration.DataReadCacheConfiguration.SizingMode != nil {
				f4f5.SizingMode = svcsdktypes.LustreReadCacheSizingMode(*r.ko.Spec.LustreConfiguration.DataReadCacheConfiguration.SizingMode)
			}
			f4.DataReadCacheConfiguration = f4f5
		}
		if r.ko.Spec.LustreConfiguration.DeploymentType != nil {
			f4.DeploymentType = svcsdktypes.LustreDeploymentType(*r.ko.Spec.LustreConfiguration.DeploymentType)
		}
		if r.ko.Spec.LustreConfiguration.DriveCacheType != nil {
			f4.DriveCacheType = svcsdktypes.DriveCacheType(*r.ko.Spec.LustreConfiguration.DriveCacheType)
		}
		if r.ko.Spec.LustreConfiguration.EfaEnabled != nil {
			f4.EfaEnabled = r.ko.Spec.LustreConfiguration.EfaEnabled
		}
		if r.ko.Spec.LustreConfiguration.ExportPath != nil {
			f4.ExportPath = r.ko.Spec.LustreConfiguration.ExportPath
		}
		if r.ko.Spec.LustreConfiguration.ImportPath != nil {
			f4.ImportPath = r.ko.Spec.LustreConfiguration.ImportPath
		}
		if r.ko.Spec.LustreConfiguration.ImportedFileChunkSize != nil {
			importedFileChunkSizeCopy0 := *r.ko.Spec.LustreConfiguration.ImportedFileChunkSize
			if importedFileChunkSizeCopy0 > math.MaxInt32 || importedFileChunkSizeCopy0 < math.MinInt32 {
				return nil, fmt.Errorf("error: field ImportedFileChunkSize is of type int32")
			}
			importedFileChunkSizeCopy := int32(importedFileChunkSizeCopy0)
			f4.ImportedFileChunkSize = &importedFileChunkSizeCopy
		}
		if r.ko.Spec.LustreConfiguration.LogConfiguration != nil {
			f4f12 := &svcsdktypes.LustreLogCreateConfiguration{}
			if r.ko.Spec.LustreConfiguration.LogConfiguration.Destination != nil {
				f4f12.Destination = r.ko.Spec.LustreConfiguration.LogConfiguration.Destination
			}
			if r.ko.Spec.LustreConfiguration.LogConfiguration.Level != nil {
				f4f12.Level = svcsdktypes.LustreAccessAuditLogLevel(*r.ko.Spec.LustreConfiguration.LogConfiguration.Level)
			}
			f4.LogConfiguration = f4f12
		}
		if r.ko.Spec.LustreConfiguration.MetadataConfiguration != nil {
			f4f13 := &svcsdktypes.CreateFileSystemLustreMetadataConfiguration{}
			if r.ko.Spec.LustreConfiguration.MetadataConfiguration.IOPS != nil {
				iopsCopy0 := *r.ko.Spec.LustreConfiguration.MetadataConfiguration.IOPS
				if iopsCopy0 > math.MaxInt32 || iopsCopy0 < math.MinInt32 {
					return nil, fmt.Errorf("error: field Iops is of type int32")
				}
				iopsCopy := int32(iopsCopy0)
				f4f13.Iops = &iopsCopy
			}
			if r.ko.Spec.LustreConfiguration.MetadataConfiguration.Mode != nil {
				f4f13.Mode = svcsdktypes.MetadataConfigurationMode(*r.ko.Spec.LustreConfiguration.MetadataConfiguration.Mode)
			}
			f4.MetadataConfiguration = f4f13
		}
		if r.ko.Spec.LustreConfiguration.PerUnitStorageThroughput != nil {
			perUnitStorageThroughputCopy0 := *r.ko.Spec.LustreConfiguration.PerUnitStorageThroughput
			if perUnitStorageThroughputCopy0 > math.MaxInt32 || perUnitStorageThroughputCopy0 < math.MinInt32 {
				return nil, fmt.Errorf("error: field PerUnitStorageThroughput is of type int32")
			}
			perUnitStorageThroughputCopy := int32(perUnitStorageThroughputCopy0)
			f4.PerUnitStorageThroughput = &perUnitStorageThroughputCopy
		}
		if r.ko.Spec.LustreConfiguration.RootSquashConfiguration != nil {
			f4f15 := &svcsdktypes.LustreRootSquashConfiguration{}
			if r.ko.Spec.LustreConfiguration.RootSquashConfiguration.NoSquashNids != nil {
				f4f15.NoSquashNids = aws.ToStringSlice(r.ko.Spec.LustreConfiguration.RootSquashConfiguration.NoSquashNids)
			}
			if r.ko.Spec.LustreConfiguration.RootSquashConfiguration.RootSquash != nil {
				f4f15.RootSquash = r.ko.Spec.LustreConfiguration.RootSquashConfiguration.RootSquash
			}
			f4.RootSquashConfiguration = f4f15
		}
		if r.ko.Spec.LustreConfiguration.ThroughputCapacity != nil {
			throughputCapacityCopy0 := *r.ko.Spec.LustreConfiguration.ThroughputCapacity
			if throughputCapacityCopy0 > math.MaxInt32 || throughputCapacityCopy0 < math.MinInt32 {
				return nil, fmt.Errorf("error: field ThroughputCapacity is of type int32")
			}
			throughputCapacityCopy := int32(throughputCapacityCopy0)
			f4.ThroughputCapacity = &throughputCapacityCopy
		}
		if r.ko.Spec.LustreConfiguration.WeeklyMaintenanceStartTime != nil {
			f4.WeeklyMaintenanceStartTime = r.ko.Spec.LustreConfiguration.WeeklyMaintenanceStartTime
		}
		res.LustreConfiguration = f4
	}
	if r.ko.Spec.NetworkType != nil {
		res.NetworkType = svcsdktypes.NetworkType(*r.ko.Spec.NetworkType)
	}
	if r.ko.Spec.OntapConfiguration != nil {
		f6 := &svcsdktypes.CreateFileSystemOntapConfiguration{}
		if r.ko.Spec.OntapConfiguration.AutomaticBackupRetentionDays != nil {
			automaticBackupRetentionDaysCopy0 := *r.ko.Spec.OntapConfiguration.AutomaticBackupRetentionDays
			if automaticBackupRetentionDaysCopy0 > math.MaxInt32 || automaticBackupRetentionDaysCopy0 < math.MinInt32 {
				return nil, fmt.Errorf("error: field AutomaticBackupRetentionDays is of type int32")
			}
			automaticBackupRetentionDaysCopy := int32(automaticBackupRetentionDaysCopy0)
			f6.AutomaticBackupRetentionDays = &automaticBackupRetentionDaysCopy
		}
		if r.ko.Spec.OntapConfiguration.DailyAutomaticBackupStartTime != nil {
			f6.DailyAutomaticBackupStartTime = r.ko.Spec.OntapConfiguration.DailyAutomaticBackupStartTime
		}
		if r.ko.Spec.OntapConfiguration.DeploymentType != nil {
			f6.DeploymentType = svcsdktypes.OntapDeploymentType(*r.ko.Spec.OntapConfiguration.DeploymentType)
		}
		if r.ko.Spec.OntapConfiguration.DiskIOPSConfiguration != nil {
			f6f3 := &svcsdktypes.DiskIopsConfiguration{}
			if r.ko.Spec.OntapConfiguration.DiskIOPSConfiguration.IOPS != nil {
				f6f3.Iops = r.ko.Spec.OntapConfiguration.DiskIOPSConfiguration.IOPS
			}
			if r.ko.Spec.OntapConfiguration.DiskIOPSConfiguration.Mode != nil {
				f6f3.Mode = svcsdktypes.DiskIopsConfigurationMode(*r.ko.Spec.OntapConfiguration.DiskIOPSConfiguration.Mode)
			}
			f6.DiskIopsConfiguration = f6f3
		}
		if r.ko.Spec.OntapConfiguration.EndpointIPAddressRange != nil {
			f6.EndpointIpAddressRange = r.ko.Spec.OntapConfiguration.EndpointIPAddressRange
		}
		if r.ko.Spec.OntapConfiguration.EndpointIPv6AddressRange != nil {
			f6.EndpointIpv6AddressRange = r.ko.Spec.OntapConfiguration.EndpointIPv6AddressRange
		}
		if r.ko.Spec.OntapConfiguration.FsxAdminPassword != nil {
			tmpSecret, err := rm.rr.SecretValueFromReference(ctx, r.ko.Spec.OntapConfiguration.FsxAdminPassword)
			if err != nil {
				return nil, ackrequeue.Needed(err)
			}
			if tmpSecret != "" {
				f6.FsxAdminPassword = aws.String(tmpSecret)
			}
		}
		if r.ko.Spec.OntapConfiguration.HAPairs != nil {
			hAPairsCopy0 := *r.ko.Spec.OntapConfiguration.HAPairs
			if hAPairsCopy0 > math.MaxInt32 || hAPairsCopy0 < math.MinInt32 {
				return nil, fmt.Errorf("error: field HAPairs is of type int32")
			}
			hAPairsCopy := int32(hAPairsCopy0)
			f6.HAPairs = &hAPairsCopy
		}
		if r.ko.Spec.OntapConfiguration.PreferredSubnetID != nil {
			f6.PreferredSubnetId = r.ko.Spec.OntapConfiguration.PreferredSubnetID
		}
		if r.ko.Spec.OntapConfiguration.RouteTableIDs != nil {
			f6.RouteTableIds = aws.ToStringSlice(r.ko.Spec.OntapConfiguration.RouteTableIDs)
		}
		if r.ko.Spec.OntapConfiguration.ThroughputCapacity != nil {
			throughputCapacityCopy0 := *r.ko.Spec.OntapConfiguration.ThroughputCapacity
			if throughputCapacityCopy0 > math.MaxInt32 || throughputCapacityCopy0 < math.MinInt32 {
				return nil, fmt.Errorf("error: field ThroughputCapacity is of type int32")
			}
			throughputCapacityCopy := int32(throughputCapacityCopy0)
			f6.ThroughputCapacity = &throughputCapacityCopy
		}
		if r.ko.Spec.OntapConfiguration.ThroughputCapacityPerHAPair != nil {
			throughputCapacityPerHAPairCopy0 := *r.ko.Spec.OntapConfiguration.ThroughputCapacityPerHAPair
			if throughputCapacityPerHAPairCopy0 > math.MaxInt32 || throughputCapacityPerHAPairCopy0 < math.MinInt32 {
				return nil, fmt.Errorf("error: field ThroughputCapacityPerHAPair is of type int32")
			}
			throughputCapacityPerHAPairCopy := int32(throughputCapacityPerHAPairCopy0)
			f6.ThroughputCapacityPerHAPair = &throughputCapacityPerHAPairCopy
		}
		if r.ko.Spec.OntapConfiguration.WeeklyMaintenanceStartTime != nil {
			f6.WeeklyMaintenanceStartTime = r.ko.Spec.OntapConfiguration.WeeklyMaintenanceStartTime
		}
		res.OntapConfiguration = f6
	}
	if r.ko.Spec.OpenZFSConfiguration != nil {
		f7 := &svcsdktypes.CreateFileSystemOpenZFSConfiguration{}
		if r.ko.Spec.OpenZFSConfiguration.AutomaticBackupRetentionDays != nil {
			automaticBackupRetentionDaysCopy0 := *r.ko.Spec.OpenZFSConfiguration.AutomaticBackupRetentionDays
			if automaticBackupRetentionDaysCopy0 > math.MaxInt32 || automaticBackupRetentionDaysCopy0 < math.MinInt32 {
				return nil, fmt.Errorf("error: field AutomaticBackupRetentionDays is of type int32")
			}
			automaticBackupRetentionDaysCopy := int32(automaticBackupRetentionDaysCopy0)
			f7.AutomaticBackupRetentionDays = &automaticBackupRetentionDaysCopy
		}
		if r.ko.Spec.OpenZFSConfiguration.CopyTagsToBackups != nil {
			f7.CopyTagsToBackups = r.ko.Spec.OpenZFSConfiguration.CopyTagsToBackups
		}
		if r.ko.Spec.OpenZFSConfiguration.CopyTagsToVolumes != nil {
			f7.CopyTagsToVolumes = r.ko.Spec.OpenZFSConfiguration.CopyTagsToVolumes
		}
		if r.ko.Spec.OpenZFSConfiguration.DailyAutomaticBackupStartTime != nil {
			f7.DailyAutomaticBackupStartTime = r.ko.Spec.OpenZFSConfiguration.DailyAutomaticBackupStartTime
		}
		if r.ko.Spec.OpenZFSConfiguration.DeploymentType != nil {
			f7.DeploymentType = svcsdktypes.OpenZFSDeploymentType(*r.ko.Spec.OpenZFSConfiguration.DeploymentType)
		}
		if r.ko.Spec.OpenZFSConfiguration.DiskIOPSConfiguration != nil {
			f7f5 := &svcsdktypes.DiskIopsConfiguration{}
			if r.ko.Spec.OpenZFSConfiguration.DiskIOPSConfiguration.IOPS != nil {
				f7f5.Iops = r.ko.Spec.OpenZFSConfiguration.DiskIOPSConfiguration.IOPS
			}
			if r.ko.Spec.OpenZFSConfiguration.DiskIOPSConfiguration.Mode != nil {
				f7f5.Mode = svcsdktypes.DiskIopsConfigurationMode(*r.ko.Spec.OpenZFSConfiguration.DiskIOPSConfiguration.Mode)
			}
			f7.DiskIopsConfiguration = f7f5
		}
		if r.ko.Spec.OpenZFSConfiguration.EndpointIPAddressRange != nil {
			f7.EndpointIpAddressRange = r.ko.Spec.OpenZFSConfiguration.EndpointIPAddressRange
		}
		if r.ko.Spec.OpenZFSConfiguration.EndpointIPv6AddressRange != nil {
			f7.EndpointIpv6AddressRange = r.ko.Spec.OpenZFSConfiguration.EndpointIPv6AddressRange
		}
		if r.ko.Spec.OpenZFSConfiguration.PreferredSubnetID != nil {
			f7.PreferredSubnetId = r.ko.Spec.OpenZFSConfiguration.PreferredSubnetID
		}
		if r.ko.Spec.OpenZFSConfiguration.ReadCacheConfiguration != nil {
			f7f9 := &svcsdktypes.OpenZFSReadCacheConfiguration{}
			if r.ko.Spec.OpenZFSConfiguration.ReadCacheConfiguration.SizeGiB != nil {
				sizeGiBCopy0 := *r.ko.Spec.OpenZFSConfiguration.ReadCacheConfiguration.SizeGiB
				if sizeGiBCopy0 > math.MaxInt32 || sizeGiBCopy0 < math.MinInt32 {
					return nil, fmt.Errorf("error: field SizeGiB is of type int32")
				}
				sizeGiBCopy := int32(sizeGiBCopy0)
				f7f9.SizeGiB = &sizeGiBCopy
			}
			if r.ko.Spec.OpenZFSConfiguration.ReadCacheConfiguration.SizingMode != nil {
				f7f9.SizingMode = svcsdktypes.OpenZFSReadCacheSizingMode(*r.ko.Spec.OpenZFSConfiguration.ReadCacheConfiguration.SizingMode)
			}
			f7.ReadCacheConfiguration = f7f9
		}
		if r.ko.Spec.OpenZFSConfiguration.RootVolumeConfiguration != nil {
			f7f10 := &svcsdktypes.OpenZFSCreateRootVolumeConfiguration{}
			if r.ko.Spec.OpenZFSConfiguration.RootVolumeConfiguration.CopyTagsToSnapshots != nil {
				f7f10.CopyTagsToSnapshots = r.ko.Spec.OpenZFSConfiguration.RootVolumeConfiguration.CopyTagsToSnapshots
			}
			if r.ko.Spec.OpenZFSConfiguration.RootVolumeConfiguration.DataCompressionType != nil {
				f7f10.DataCompressionType = svcsdktypes.OpenZFSDataCompressionType(*r.ko.Spec.OpenZFSConfiguration.RootVolumeConfiguration.DataCompressionType)
			}
			if r.ko.Spec.OpenZFSConfiguration.RootVolumeConfiguration.NfsExports != nil {
				f7f10f2 := []svcsdktypes.OpenZFSNfsExport{}
				for _, f7f10f2iter := range r.ko.Spec.OpenZFSConfiguration.RootVolumeConfiguration.NfsExports {
					f7f10f2elem := &svcsdktypes.OpenZFSNfsExport{}
					if f7f10f2iter.ClientConfigurations != nil {
						f7f10f2elemf0 := []svcsdktypes.OpenZFSClientConfiguration{}
						for _, f7f10f2elemf0iter := range f7f10f2iter.ClientConfigurations {
							f7f10f2elemf0elem := &svcsdktypes.OpenZFSClientConfiguration{}
							if f7f10f2elemf0iter.Clients != nil {
								f7f10f2elemf0elem.Clients = f7f10f2elemf0iter.Clients
							}
							if f7f10f2elemf0iter.Options != nil {
								f7f10f2elemf0elem.Options = aws.ToStringSlice(f7f10f2elemf0iter.Options)
							}
							f7f10f2elemf0 = append(f7f10f2elemf0, *f7f10f2elemf0elem)
						}
						f7f10f2elem.ClientConfigurations = f7f10f2elemf0
					}
					f7f10f2 = append(f7f10f2, *f7f10f2elem)
				}
				f7f10.NfsExports = f7f10f2
			}
			if r.ko.Spec.OpenZFSConfiguration.RootVolumeConfiguration.ReadOnly != nil {
				f7f10.ReadOnly = r.ko.Spec.OpenZFSConfiguration.RootVolumeConfiguration.ReadOnly
			}
			if r.ko.Spec.OpenZFSConfiguration.RootVolumeConfiguration.RecordSizeKiB != nil {
				recordSizeKiBCopy0 := *r.ko.Spec.OpenZFSConfiguration.RootVolumeConfiguration.RecordSizeKiB
				if recordSizeKiBCopy0 > math.MaxInt32 || recordSizeKiBCopy0 < math.MinInt32 {
					return nil, fmt.Errorf("error: field RecordSizeKiB is of type int32")
				}
				recordSizeKiBCopy := int32(recordSizeKiBCopy0)
				f7f10.RecordSizeKiB = &recordSizeKiBCopy
			}
			if r.ko.Spec.OpenZFSConfiguration.RootVolumeConfiguration.UserAndGroupQuotas != nil {
				f7f10f5 := []svcsdktypes.OpenZFSUserOrGroupQuota{}
				for _, f7f10f5iter := range r.ko.Spec.OpenZFSConfiguration.RootVolumeConfiguration.UserAndGroupQuotas {
					f7f10f5elem := &svcsdktypes.OpenZFSUserOrGroupQuota{}
					if f7f10f5iter.ID != nil {
						idCopy0 := *f7f10f5iter.ID
						if idCopy0 > math.MaxInt32 || idCopy0 < math.MinInt32 {
							return nil, fmt.Errorf("error: field Id is of type int32")
						}
						idCopy := int32(idCopy0)
						f7f10f5elem.Id = &idCopy
					}
					if f7f10f5iter.StorageCapacityQuotaGiB != nil {
						storageCapacityQuotaGiBCopy0 := *f7f10f5iter.StorageCapacityQuotaGiB
						if storageCapacityQuotaGiBCopy0 > math.MaxInt32 || storageCapacityQuotaGiBCopy0 < math.MinInt32 {
							return nil, fmt.Errorf("error: field StorageCapacityQuotaGiB is of type int32")
						}
						storageCapacityQuotaGiBCopy := int32(storageCapacityQuotaGiBCopy0)
						f7f10f5elem.StorageCapacityQuotaGiB = &storageCapacityQuotaGiBCopy
					}
					if f7f10f5iter.Type != nil {
						f7f10f5elem.Type = svcsdktypes.OpenZFSQuotaType(*f7f10f5iter.Type)
					}
					f7f10f5 = append(f7f10f5, *f7f10f5elem)
				}
				f7f10.UserAndGroupQuotas = f7f10f5
			}
			f7.RootVolumeConfiguration = f7f10
		}
		if r.ko.Spec.OpenZFSConfiguration.RouteTableIDs != nil {
			f7.RouteTableIds = aws.ToStringSlice(r.ko.Spec.OpenZFSConfiguration.RouteTableIDs)
		}
		if r.ko.Spec.OpenZFSConfiguration.ThroughputCapacity != nil {
			throughputCapacityCopy0 := *r.ko.Spec.OpenZFSConfiguration.ThroughputCapacity
			if throughputCapacityCopy0 > math.MaxInt32 || throughputCapacityCopy0 < math.MinInt32 {
				return nil, fmt.Errorf("error: field ThroughputCapacity is of type int32")
			}
			throughputCapacityCopy := int32(throughputCapacityCopy0)
			f7.ThroughputCapacity = &throughputCapacityCopy
		}
		if r.ko.Spec.OpenZFSConfiguration.WeeklyMaintenanceStartTime != nil {
			f7.WeeklyMaintenanceStartTime = r.ko.Spec.OpenZFSConfiguration.WeeklyMaintenanceStartTime
		}
		res.OpenZFSConfiguration = f7
	}
	if r.ko.Spec.SecurityGroupIDs != nil {
		res.SecurityGroupIds = aws.ToStringSlice(r.ko.Spec.SecurityGroupIDs)
	}
	if r.ko.Spec.StorageCapacity != nil {
		storageCapacityCopy0 := *r.ko.Spec.StorageCapacity
		if storageCapacityCopy0 > math.MaxInt32 || storageCapacityCopy0 < math.MinInt32 {
			return nil, fmt.Errorf("error: field StorageCapacity is of type int32")
		}
		storageCapacityCopy := int32(storageCapacityCopy0)
		res.StorageCapacity = &storageCapacityCopy
	}
	if r.ko.Spec.StorageType != nil {
		res.StorageType = svcsdktypes.StorageType(*r.ko.Spec.StorageType)
	}
	if r.ko.Spec.SubnetIDs != nil {
		res.SubnetIds = aws.ToStringSlice(r.ko.Spec.SubnetIDs)
	}
	if r.ko.Spec.Tags != nil {
		f12 := []svcsdktypes.Tag{}
		for _, f12iter := range r.ko.Spec.Tags {
			f12elem := &svcsdktypes.Tag{}
			if f12iter.Key != nil {
				f12elem.Key = f12iter.Key
			}
			if f12iter.Value != nil {
				f12elem.Value = f12iter.Value
			}
			f12 = append(f12, *f12elem)
		}
		res.Tags = f12
	}
	if r.ko.Spec.WindowsConfiguration != nil {
		f13 := &svcsdktypes.CreateFileSystemWindowsConfiguration{}
		if r.ko.Spec.WindowsConfiguration.ActiveDirectoryID != nil {
			f13.ActiveDirectoryId = r.ko.Spec.WindowsConfiguration.ActiveDirectoryID
		}
		if r.ko.Spec.WindowsConfiguration.Aliases != nil {
			f13.Aliases = aws.ToStringSlice(r.ko.Spec.WindowsConfiguration.Aliases)
		}
		if r.ko.Spec.WindowsConfiguration.AuditLogConfiguration != nil {
			f13f2 := &svcsdktypes.WindowsAuditLogCreateConfiguration{}
			if r.ko.Spec.WindowsConfiguration.AuditLogConfiguration.AuditLogDestination != nil {
				f13f2.AuditLogDestination = r.ko.Spec.WindowsConfiguration.AuditLogConfiguration.AuditLogDestination
			}
			if r.ko.Spec.WindowsConfiguration.AuditLogConfiguration.FileAccessAuditLogLevel != nil {
				f13f2.FileAccessAuditLogLevel = svcsdktypes.WindowsAccessAuditLogLevel(*r.ko.Spec.WindowsConfiguration.AuditLogConfiguration.FileAccessAuditLogLevel)
			}
			if r.ko.Spec.WindowsConfiguration.AuditLogConfiguration.FileShareAccessAuditLogLevel != nil {
				f13f2.FileShareAccessAuditLogLevel = svcsdktypes.WindowsAccessAuditLogLevel(*r.ko.Spec.WindowsConfiguration.AuditLogConfiguration.FileShareAccessAuditLogLevel)
			}
			f13.AuditLogConfiguration = f13f2
		}
		if r.ko.Spec.WindowsConfiguration.AutomaticBackupRetentionDays != nil {
			automaticBackupRetentionDaysCopy0 := *r.ko.Spec.WindowsConfiguration.AutomaticBackupRetentionDays
			if automaticBackupRetentionDaysCopy0 > math.MaxInt32 || automaticBackupRetentionDaysCopy0 < math.MinInt32 {
				return nil, fmt.Errorf("error: field AutomaticBackupRetentionDays is of type int32")
			}
			automaticBackupRetentionDaysCopy := int32(automaticBackupRetentionDaysCopy0)
			f13.AutomaticBackupRetentionDays = &automaticBackupRetentionDaysCopy
		}
		if r.ko.Spec.WindowsConfiguration.CopyTagsToBackups != nil {
			f13.CopyTagsToBackups = r.ko.Spec.WindowsConfiguration.CopyTagsToBackups
		}
		if r.ko.Spec.WindowsConfiguration.DailyAutomaticBackupStartTime != nil {
			f13.DailyAutomaticBackupStartTime = r.ko.Spec.WindowsConfiguration.DailyAutomaticBackupStartTime
		}
		if r.ko.Spec.WindowsConfiguration.DeploymentType != nil {
			f13.DeploymentType = svcsdktypes.WindowsDeploymentType(*r.ko.Spec.WindowsConfiguration.DeploymentType)
		}
		if r.ko.Spec.WindowsConfiguration.DiskIOPSConfiguration != nil {
			f13f7 := &svcsdktypes.DiskIopsConfiguration{}
			if r.ko.Spec.WindowsConfiguration.DiskIOPSConfiguration.IOPS != nil {
				f13f7.Iops = r.ko.Spec.WindowsConfiguration.DiskIOPSConfiguration.IOPS
			}
			if r.ko.Spec.WindowsConfiguration.DiskIOPSConfiguration.Mode != nil {
				f13f7.Mode = svcsdktypes.DiskIopsConfigurationMode(*r.ko.Spec.WindowsConfiguration.DiskIOPSConfiguration.Mode)
			}
			f13.DiskIopsConfiguration = f13f7
		}
		if r.ko.Spec.WindowsConfiguration.FsrmConfiguration != nil {
			f13f8 := &svcsdktypes.WindowsFsrmConfiguration{}
			if r.ko.Spec.WindowsConfiguration.FsrmConfiguration.EventLogDestination != nil {
				f13f8.EventLogDestination = r.ko.Spec.WindowsConfiguration.FsrmConfiguration.EventLogDestination
			}
			if r.ko.Spec.WindowsConfiguration.FsrmConfiguration.FsrmServiceEnabled != nil {
				f13f8.FsrmServiceEnabled = r.ko.Spec.WindowsConfiguration.FsrmConfiguration.FsrmServiceEnabled
			}
			f13.FsrmConfiguration = f13f8
		}
		if r.ko.Spec.WindowsConfiguration.PreferredSubnetID != nil {
			f13.PreferredSubnetId = r.ko.Spec.WindowsConfiguration.PreferredSubnetID
		}
		if r.ko.Spec.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration != nil {
			f13f10 := &svcsdktypes.SelfManagedActiveDirectoryConfiguration{}
			if r.ko.Spec.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.DNSIPs != nil {
				f13f10.DnsIps = aws.ToStringSlice(r.ko.Spec.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.DNSIPs)
			}
			if r.ko.Spec.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.DomainJoinServiceAccountSecret != nil {
				f13f10.DomainJoinServiceAccountSecret = r.ko.Spec.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.DomainJoinServiceAccountSecret
			}
			if r.ko.Spec.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.DomainName != nil {
				f13f10.DomainName = r.ko.Spec.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.DomainName
			}
			if r.ko.Spec.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.FileSystemAdministratorsGroup != nil {
				f13f10.FileSystemAdministratorsGroup = r.ko.Spec.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.FileSystemAdministratorsGroup
			}
			if r.ko.Spec.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.OrganizationalUnitDistinguishedName != nil {
				f13f10.OrganizationalUnitDistinguishedName = r.ko.Spec.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.OrganizationalUnitDistinguishedName
			}
			if r.ko.Spec.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.Password != nil {
				tmpSecret, err := rm.rr.SecretValueFromReference(ctx, r.ko.Spec.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.Password)
				if err != nil {
					return nil, ackrequeue.Needed(err)
				}
				if tmpSecret != "" {
					f13f10.Password = aws.String(tmpSecret)
				}
			}
			if r.ko.Spec.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.UserName != nil {
				f13f10.UserName = r.ko.Spec.WindowsConfiguration.SelfManagedActiveDirectoryConfiguration.UserName
			}
			f13.SelfManagedActiveDirectoryConfiguration = f13f10
		}
		if r.ko.Spec.WindowsConfiguration.ThroughputCapacity != nil {
			throughputCapacityCopy0 := *r.ko.Spec.WindowsConfiguration.ThroughputCapacity
			if throughputCapacityCopy0 > math.MaxInt32 || throughputCapacityCopy0 < math.MinInt32 {
				return nil, fmt.Errorf("error: field ThroughputCapacity is of type int32")
			}
			throughputCapacityCopy := int32(throughputCapacityCopy0)
			f13.ThroughputCapacity = &throughputCapacityCopy
		}
		if r.ko.Spec.WindowsConfiguration.WeeklyMaintenanceStartTime != nil {
			f13.WeeklyMaintenanceStartTime = r.ko.Spec.WindowsConfiguration.WeeklyMaintenanceStartTime
		}
		res.WindowsConfiguration = f13
	}

	return res, nil
}

// sdkUpdate patches the supplied resource in the backend AWS service API and
// returns a new resource with updated fields.
func (rm *resourceManager) sdkUpdate(
	ctx context.Context,
	desired *resource,
	latest *resource,
	delta *ackcompare.Delta,
) (*resource, error) {
	return rm.customUpdateFileSystem(ctx, desired, latest, delta)
}

// sdkDelete deletes the supplied resource in the backend AWS service API
func (rm *resourceManager) sdkDelete(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkDelete")
	defer func() {
		exit(err)
	}()
	// ReadOne runs immediately before Delete, so Status.Lifecycle is current.
	// FSx rejects DeleteFileSystem for a file system already DELETING, so
	// requeue rather than making a call that can only fail. Return `r` rather
	// than nil (as rds/eks/elasticache/memorydb do) so the runtime has a
	// resource to patch status from during the wait.
	if isDeleting(r) {
		return r, requeueWaitWhileDeleting
	}

	input, err := rm.newDeleteRequestPayload(r)
	if err != nil {
		return nil, err
	}
	// In hooks.go because it needs the pkg/util import, which this template
	// cannot add to sdk.go.
	if err = setDeleteFileSystemConfiguration(r, input); err != nil {
		return nil, err
	}

	var resp *svcsdk.DeleteFileSystemOutput
	_ = resp
	resp, err = rm.sdkapi.DeleteFileSystem(ctx, input)
	rm.metrics.RecordAPICall("DELETE", "DeleteFileSystem", err)
	// Delete is async: FSx stays DELETING for 5-10 min while its ENIs are torn
	// down, so requeue instead of dropping the finalizer -- otherwise the ec2
	// Subnet/SecurityGroup CRs this references fail to delete. Later reconciles
	// short-circuit in sdk_delete_pre_build_request until FileSystemNotFound.
	if err == nil {
		return r, requeueWaitWhileDeleting
	}

	return nil, err
}

// newDeleteRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Delete API call for the resource
func (rm *resourceManager) newDeleteRequestPayload(
	r *resource,
) (*svcsdk.DeleteFileSystemInput, error) {
	res := &svcsdk.DeleteFileSystemInput{}

	if r.ko.Status.FileSystemID != nil {
		res.FileSystemId = r.ko.Status.FileSystemID
	}

	return res, nil
}

// setStatusDefaults sets default properties into supplied custom resource
func (rm *resourceManager) setStatusDefaults(
	ko *svcapitypes.FileSystem,
) {
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if ko.Status.ACKResourceMetadata.Region == nil {
		ko.Status.ACKResourceMetadata.Region = &rm.awsRegion
	}
	if ko.Status.ACKResourceMetadata.Partition == nil {
		ko.Status.ACKResourceMetadata.Partition = &rm.awsPartition
	}
	if ko.Status.ACKResourceMetadata.OwnerAccountID == nil {
		ko.Status.ACKResourceMetadata.OwnerAccountID = &rm.awsAccountID
	}
	if ko.Status.Conditions == nil {
		ko.Status.Conditions = []*ackv1alpha1.Condition{}
	}
}

// updateConditions returns updated resource, true; if conditions were updated
// else it returns nil, false
func (rm *resourceManager) updateConditions(
	r *resource,
	onSuccess bool,
	err error,
) (*resource, bool) {
	ko := r.ko.DeepCopy()
	rm.setStatusDefaults(ko)

	// Terminal condition
	var terminalCondition *ackv1alpha1.Condition = nil
	var recoverableCondition *ackv1alpha1.Condition = nil
	var syncCondition *ackv1alpha1.Condition = nil
	for _, condition := range ko.Status.Conditions {
		if condition.Type == ackv1alpha1.ConditionTypeTerminal {
			terminalCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeRecoverable {
			recoverableCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeResourceSynced {
			syncCondition = condition
		}
	}
	var termError *ackerr.TerminalError
	if rm.terminalAWSError(err) || err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
		if terminalCondition == nil {
			terminalCondition = &ackv1alpha1.Condition{
				Type: ackv1alpha1.ConditionTypeTerminal,
			}
			ko.Status.Conditions = append(ko.Status.Conditions, terminalCondition)
		}
		var errorMessage = ""
		if err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
			errorMessage = err.Error()
		} else {
			awsErr, _ := ackerr.AWSError(err)
			errorMessage = awsErr.Error()
		}
		terminalCondition.Status = corev1.ConditionTrue
		terminalCondition.Message = &errorMessage
	} else {
		// Clear the terminal condition if no longer present
		if terminalCondition != nil {
			terminalCondition.Status = corev1.ConditionFalse
			terminalCondition.Message = nil
		}
		// Handling Recoverable Conditions
		if err != nil {
			if recoverableCondition == nil {
				// Add a new Condition containing a non-terminal error
				recoverableCondition = &ackv1alpha1.Condition{
					Type: ackv1alpha1.ConditionTypeRecoverable,
				}
				ko.Status.Conditions = append(ko.Status.Conditions, recoverableCondition)
			}
			recoverableCondition.Status = corev1.ConditionTrue
			awsErr, _ := ackerr.AWSError(err)
			errorMessage := err.Error()
			if awsErr != nil {
				errorMessage = awsErr.Error()
			}
			recoverableCondition.Message = &errorMessage
		} else if recoverableCondition != nil {
			recoverableCondition.Status = corev1.ConditionFalse
			recoverableCondition.Message = nil
		}
	}
	// Required to avoid the "declared but not used" error in the default case
	_ = syncCondition
	if terminalCondition != nil || recoverableCondition != nil || syncCondition != nil {
		return &resource{ko}, true // updated
	}
	return nil, false // not updated
}

// terminalAWSError returns awserr, true; if the supplied error is an aws Error type
// and if the exception indicates that it is a Terminal exception
// 'Terminal' exception are specified in generator configuration
func (rm *resourceManager) terminalAWSError(err error) bool {
	if err == nil {
		return false
	}

	var terminalErr smithy.APIError
	if !errors.As(err, &terminalErr) {
		return false
	}
	switch terminalErr.ErrorCode() {
	case "IncompatibleParameterError",
		"InvalidExportPath",
		"InvalidImportPath",
		"InvalidNetworkSettings",
		"InvalidPerUnitStorageThroughput",
		"MissingFileSystemConfiguration",
		"UnsupportedOperation":
		return true
	default:
		return false
	}
}
