// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// FileSystemSpec defines the desired state of FileSystem.
//
// A description of a specific Amazon FSx file system.
type FileSystemSpec struct {

	// The type of Amazon FSx file system to create. Valid values are WINDOWS, LUSTRE,
	// ONTAP, and OPENZFS.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
	// +kubebuilder:validation:Required
	FileSystemType *string `json:"fileSystemType"`
	// For FSx for Lustre file systems, sets the Lustre version for the file system
	// that you're creating. Valid values are 2.10, 2.12, and 2.15:
	//
	//    * 2.10 is supported by the Scratch and Persistent_1 Lustre deployment
	//    types.
	//
	//    * 2.12 is supported by all Lustre deployment types, except for PERSISTENT_2
	//    with a metadata configuration mode.
	//
	//    * 2.15 is supported by all Lustre deployment types and is recommended
	//    for all new file systems.
	//
	// Default value is 2.10, except for the following deployments:
	//
	//    * Default value is 2.12 when DeploymentType is set to PERSISTENT_2 without
	//    a metadata configuration mode.
	//
	//    * Default value is 2.15 when DeploymentType is set to PERSISTENT_2 with
	//    a metadata configuration mode.
	//
	// Regex Pattern: `^[0-9](.[0-9]*)*$`
	FileSystemTypeVersion *string `json:"fileSystemTypeVersion,omitempty"`
	// Regex Pattern: `^.{1,2048}$`
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
	KMSKeyID            *string                                  `json:"kmsKeyID,omitempty"`
	KMSKeyRef           *ackv1alpha1.AWSResourceReferenceWrapper `json:"kmsKeyRef,omitempty"`
	LustreConfiguration *CreateFileSystemLustreConfiguration     `json:"lustreConfiguration,omitempty"`
	// The network type of the Amazon FSx file system that you are creating. Valid
	// values are IPV4 (which supports IPv4 only) and DUAL (for dual-stack mode,
	// which supports both IPv4 and IPv6). The default is IPV4. Supported for FSx
	// for OpenZFS, FSx for ONTAP, and FSx for Windows File Server file systems.
	NetworkType        *string                             `json:"networkType,omitempty"`
	OntapConfiguration *CreateFileSystemOntapConfiguration `json:"ontapConfiguration,omitempty"`
	// The OpenZFS configuration for the file system that's being created.
	OpenZFSConfiguration *CreateFileSystemOpenZFSConfiguration `json:"openZFSConfiguration,omitempty"`
	// A list of IDs specifying the security groups to apply to all network interfaces
	// created for file system access. This list isn't returned in later requests
	// to describe the file system.
	//
	// You must specify a security group if you are creating a Multi-AZ FSx for
	// ONTAP file system in a VPC subnet that has been shared with you.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
	SecurityGroupIDs  []*string                                  `json:"securityGroupIDs,omitempty"`
	SecurityGroupRefs []*ackv1alpha1.AWSResourceReferenceWrapper `json:"securityGroupRefs,omitempty"`
	// Sets the storage capacity of the file system that you're creating, in gibibytes
	// (GiB).
	//
	// FSx for Lustre file systems - The amount of storage capacity that you can
	// configure depends on the value that you set for StorageType and the Lustre
	// DeploymentType, as follows:
	//
	//    * For SCRATCH_2, PERSISTENT_2, and PERSISTENT_1 deployment types using
	//    SSD storage type, the valid values are 1200 GiB, 2400 GiB, and increments
	//    of 2400 GiB.
	//
	//    * For PERSISTENT_1 HDD file systems, valid values are increments of 6000
	//    GiB for 12 MB/s/TiB file systems and increments of 1800 GiB for 40 MB/s/TiB
	//    file systems.
	//
	//    * For SCRATCH_1 deployment type, valid values are 1200 GiB, 2400 GiB,
	//    and increments of 3600 GiB.
	//
	// FSx for ONTAP file systems - The amount of storage capacity that you can
	// configure depends on the value of the HAPairs property. The minimum value
	// is calculated as 1,024 * HAPairs and the maximum is calculated as 524,288
	// * HAPairs.
	//
	// FSx for OpenZFS file systems - The amount of storage capacity that you can
	// configure is from 64 GiB up to 524,288 GiB (512 TiB).
	//
	// FSx for Windows File Server file systems - The amount of storage capacity
	// that you can configure depends on the value that you set for StorageType
	// as follows:
	//
	//    * For SSD storage, valid values are 32 GiB-65,536 GiB (64 TiB).
	//
	//    * For HDD storage, valid values are 2000 GiB-65,536 GiB (64 TiB).
	StorageCapacity *int64 `json:"storageCapacity,omitempty"`
	// Sets the storage class for the file system that you're creating. Valid values
	// are SSD, HDD, and INTELLIGENT_TIERING.
	//
	//    * Set to SSD to use solid state drive storage. SSD is supported on all
	//    Windows, Lustre, ONTAP, and OpenZFS deployment types.
	//
	//    * Set to HDD to use hard disk drive storage, which is supported on SINGLE_AZ_2
	//    and MULTI_AZ_1 Windows file system deployment types, and on PERSISTENT_1
	//    Lustre file system deployment types.
	//
	//    * Set to INTELLIGENT_TIERING to use fully elastic, intelligently-tiered
	//    storage. Intelligent-Tiering is only available for OpenZFS file systems
	//    with the Multi-AZ deployment type and for Lustre file systems with the
	//    Persistent_2 deployment type.
	//
	// Default value is SSD. For more information, see Storage type options (https://docs.aws.amazon.com/fsx/latest/WindowsGuide/optimize-fsx-costs.html#storage-type-options)
	// in the FSx for Windows File Server User Guide, FSx for Lustre storage classes
	// (https://docs.aws.amazon.com/fsx/latest/LustreGuide/using-fsx-lustre.html#lustre-storage-classes)
	// in the FSx for Lustre User Guide, and Working with Intelligent-Tiering (https://docs.aws.amazon.com/fsx/latest/OpenZFSGuide/performance-intelligent-tiering)
	// in the Amazon FSx for OpenZFS User Guide.
	StorageType *string `json:"storageType,omitempty"`
	// Specifies the IDs of the subnets that the file system will be accessible
	// from. For Windows and ONTAP MULTI_AZ_1 deployment types,provide exactly two
	// subnet IDs, one for the preferred file server and one for the standby file
	// server. You specify one of these subnets as the preferred subnet using the
	// WindowsConfiguration > PreferredSubnetID or OntapConfiguration > PreferredSubnetID
	// properties. For more information about Multi-AZ file system configuration,
	// see Availability and durability: Single-AZ and Multi-AZ file systems (https://docs.aws.amazon.com/fsx/latest/WindowsGuide/high-availability-multiAZ.html)
	// in the Amazon FSx for Windows User Guide and Availability and durability
	// (https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/high-availability-multiAZ.html)
	// in the Amazon FSx for ONTAP User Guide.
	//
	// For Windows SINGLE_AZ_1 and SINGLE_AZ_2 and all Lustre deployment types,
	// provide exactly one subnet ID. The file server is launched in that subnet's
	// Availability Zone.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
	SubnetIDs  []*string                                  `json:"subnetIDs,omitempty"`
	SubnetRefs []*ackv1alpha1.AWSResourceReferenceWrapper `json:"subnetRefs,omitempty"`
	// The tags to apply to the file system that's being created. The key value
	// of the Name tag appears in the console as the file system name.
	Tags []*Tag `json:"tags,omitempty"`
	// The Microsoft Windows configuration for the file system that's being created.
	WindowsConfiguration *CreateFileSystemWindowsConfiguration `json:"windowsConfiguration,omitempty"`
}

// FileSystemStatus defines the observed state of FileSystem
type FileSystemStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	// +kubebuilder:validation:Optional
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRs managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	// +kubebuilder:validation:Optional
	Conditions []*ackv1alpha1.Condition `json:"conditions"`
	// The time that the file system was created, in seconds (since 1970-01-01T00:00:00Z),
	// also known as Unix time.
	// +kubebuilder:validation:Optional
	CreationTime *metav1.Time `json:"creationTime,omitempty"`
	// The Domain Name System (DNS) name for the file system.
	//
	// Regex Pattern: `^((fs|fc)i?-[0-9a-f]{8,}\..{4,253})$`
	// +kubebuilder:validation:Optional
	DNSName *string `json:"dnsName,omitempty"`
	// +kubebuilder:validation:Optional
	FailureDetails *FileSystemFailureDetails `json:"failureDetails,omitempty"`
	// The system-generated, unique 17-digit ID of the file system.
	//
	// Regex Pattern: `^(fs-[0-9a-f]{8,})$`
	// +kubebuilder:validation:Optional
	FileSystemID *string `json:"fileSystemID,omitempty"`
	// +kubebuilder:validation:Optional
	LastAppliedFsxAdminPasswordRef *string `json:"lastAppliedFsxAdminPasswordRef,omitempty"`
	// +kubebuilder:validation:Optional
	LastAppliedImmutableFields *string `json:"lastAppliedImmutableFields,omitempty"`
	// +kubebuilder:validation:Optional
	LastAppliedSelfManagedADPasswordRef *string `json:"lastAppliedSelfManagedADPasswordRef,omitempty"`
	// The lifecycle status of the file system. The following are the possible values
	// and what they mean:
	//
	//    * AVAILABLE - The file system is in a healthy state, and is reachable
	//    and available for use.
	//
	//    * CREATING - Amazon FSx is creating the new file system.
	//
	//    * DELETING - Amazon FSx is deleting an existing file system.
	//
	//    * FAILED - An existing file system has experienced an unrecoverable failure.
	//    When creating a new file system, Amazon FSx was unable to create the file
	//    system.
	//
	//    * MISCONFIGURED - The file system is in a failed but recoverable state.
	//
	//    * MISCONFIGURED_UNAVAILABLE - (Amazon FSx for Windows File Server only)
	//    The file system is currently unavailable due to a change in your Active
	//    Directory configuration.
	//
	//    * UPDATING - The file system is undergoing a customer-initiated update.
	// +kubebuilder:validation:Optional
	Lifecycle *string `json:"lifecycle,omitempty"`
	// The IDs of the elastic network interfaces from which a specific file system
	// is accessible. The elastic network interface is automatically created in
	// the same virtual private cloud (VPC) that the Amazon FSx file system was
	// created in. For more information, see Elastic Network Interfaces (https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-eni.html)
	// in the Amazon EC2 User Guide.
	//
	// For an Amazon FSx for Windows File Server file system, you can have one network
	// interface ID. For an Amazon FSx for Lustre file system, you can have more
	// than one.
	// +kubebuilder:validation:Optional
	NetworkInterfaceIDs []*string `json:"networkInterfaceIDs,omitempty"`
	// The Amazon Web Services account that created the file system. If the file
	// system was created by a user in IAM Identity Center, the Amazon Web Services
	// account to which the IAM user belongs is the owner.
	//
	// Regex Pattern: `^\d{12}$`
	// +kubebuilder:validation:Optional
	OwnerID *string `json:"ownerID,omitempty"`
	// The ID of the primary virtual private cloud (VPC) for the file system.
	//
	// Regex Pattern: `^(vpc-[0-9a-f]{8,})$`
	// +kubebuilder:validation:Optional
	VPCID *string `json:"vpcID,omitempty"`
}

// FileSystem is the Schema for the FileSystems API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="ID",type=string,priority=0,JSONPath=`.status.fileSystemID`
// +kubebuilder:printcolumn:name="TYPE",type=string,priority=0,JSONPath=`.spec.fileSystemType`
// +kubebuilder:printcolumn:name="STORAGE",type=integer,priority=0,JSONPath=`.spec.storageCapacity`
// +kubebuilder:printcolumn:name="DNSNAME",type=string,priority=1,JSONPath=`.status.dnsName`
// +kubebuilder:printcolumn:name="STATE",type=string,priority=0,JSONPath=`.status.lifecycle`
// +kubebuilder:printcolumn:name="Synced",type="string",priority=0,JSONPath=".status.conditions[?(@.type==\"ACK.ResourceSynced\")].status"
// +kubebuilder:printcolumn:name="Age",type="date",priority=0,JSONPath=".metadata.creationTimestamp"
type FileSystem struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              FileSystemSpec   `json:"spec,omitempty"`
	Status            FileSystemStatus `json:"status,omitempty"`
}

// FileSystemList contains a list of FileSystem
// +kubebuilder:object:root=true
type FileSystemList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []FileSystem `json:"items"`
}

func init() {
	SchemeBuilder.Register(&FileSystem{}, &FileSystemList{})
}
